//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMC.Portal.Business.HSSPortalAPOSlitter
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName = "HSSPortalAPOSlitter.ZWS_HSS_PORTAL_APO_SLITTER")]
    public interface ZWS_HSS_PORTAL_APO_SLITTER
    {

        [System.ServiceModel.OperationContractAttribute(Action = "urn:sap-com:document:sap:soap:functions:mc-style:ZWS_HSS_PORTAL_APO_SLITTER:ZfmGe" +
            "tSosapoSlitPatternRequest", ReplyAction = "urn:sap-com:document:sap:soap:functions:mc-style:ZWS_HSS_PORTAL_APO_SLITTER:ZfmGe" +
            "tSosapoSlitPatternResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        HSSPortalAPOSlitter.ZfmGetSosapoSlitPatternResponse ZfmGetSosapoSlitPatternAsync(HSSPortalAPOSlitter.ZfmGetSosapoSlitPatternRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:sap-com:document:sap:soap:functions:mc-style:ZWS_HSS_PORTAL_APO_SLITTER:ZfmGe" +
            "tSosapoTandemScheduleRequest", ReplyAction = "urn:sap-com:document:sap:soap:functions:mc-style:ZWS_HSS_PORTAL_APO_SLITTER:ZfmGe" +
            "tSosapoTandemScheduleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        HSSPortalAPOSlitter.ZfmGetSosapoTandemScheduleResponse ZfmGetSosapoTandemScheduleAsync(HSSPortalAPOSlitter.ZfmGetSosapoTandemScheduleRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:sap-com:document:sap:soap:functions:mc-style:ZWS_HSS_PORTAL_APO_SLITTER:ZfmPl" +
            "anningProductExtractRequest", ReplyAction = "urn:sap-com:document:sap:soap:functions:mc-style:ZWS_HSS_PORTAL_APO_SLITTER:ZfmPl" +
            "anningProductExtractResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        HSSPortalAPOSlitter.ZfmPlanningProductExtractResponse ZfmPlanningProductExtractAsync(HSSPortalAPOSlitter.ZfmPlanningProductExtractRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmGetSosapoSlitPattern
    {

        private ZstPlant[] itPlantField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ZstPlant[] ItPlant
        {
            get
            {
                return this.itPlantField;
            }
            set
            {
                this.itPlantField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstPlant
    {

        private string werksField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Werks
        {
            get
            {
                return this.werksField;
            }
            set
            {
                this.werksField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zplanningproduct
    {

        private string mandtField;

        private string plantField;

        private string resourceNameField;

        private string planningMaterialField;

        private string familyField;

        private decimal diameterField;

        private decimal tubeSize1Field;

        private decimal tubeSize2Field;

        private string shapeField;

        private decimal gaugeField;

        private string gradeGroupField;

        private decimal runRateField;

        private string primSlitcoilField;

        private decimal lossField;

        private string primMastercoilField;

        private string lastBlockAllowedField;

        private string cycletimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Mandt
        {
            get
            {
                return this.mandtField;
            }
            set
            {
                this.mandtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string ResourceName
        {
            get
            {
                return this.resourceNameField;
            }
            set
            {
                this.resourceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string PlanningMaterial
        {
            get
            {
                return this.planningMaterialField;
            }
            set
            {
                this.planningMaterialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Family
        {
            get
            {
                return this.familyField;
            }
            set
            {
                this.familyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public decimal Diameter
        {
            get
            {
                return this.diameterField;
            }
            set
            {
                this.diameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public decimal TubeSize1
        {
            get
            {
                return this.tubeSize1Field;
            }
            set
            {
                this.tubeSize1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public decimal TubeSize2
        {
            get
            {
                return this.tubeSize2Field;
            }
            set
            {
                this.tubeSize2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string Shape
        {
            get
            {
                return this.shapeField;
            }
            set
            {
                this.shapeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public decimal Gauge
        {
            get
            {
                return this.gaugeField;
            }
            set
            {
                this.gaugeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string GradeGroup
        {
            get
            {
                return this.gradeGroupField;
            }
            set
            {
                this.gradeGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public decimal RunRate
        {
            get
            {
                return this.runRateField;
            }
            set
            {
                this.runRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string PrimSlitcoil
        {
            get
            {
                return this.primSlitcoilField;
            }
            set
            {
                this.primSlitcoilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public decimal Loss
        {
            get
            {
                return this.lossField;
            }
            set
            {
                this.lossField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public string PrimMastercoil
        {
            get
            {
                return this.primMastercoilField;
            }
            set
            {
                this.primMastercoilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public string LastBlockAllowed
        {
            get
            {
                return this.lastBlockAllowedField;
            }
            set
            {
                this.lastBlockAllowedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public string Cycletime
        {
            get
            {
                return this.cycletimeField;
            }
            set
            {
                this.cycletimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZatasSosTandemSchedule
    {

        private string plantField;

        private string bundlingWorkCenterField;

        private string materialNumberField;

        private decimal plannedQuantityField;

        private string startDateField;

        private string finishDateField;

        private string slitCoilField;

        private decimal receivedQuantityField;

        private string sourceField;

        private string familyField;

        private string blockNumberField;

        private string bFixedField;

        private decimal gaugeField;

        private string gradeGroupField;

        private decimal combFreeCapField;

        private decimal stockOrdField;

        private decimal stockReqField;

        private decimal blkHrsField;

        private decimal stkordHrsField;

        private string stkLevelField;

        private decimal planHrsField;

        private decimal bookHrsField;

        private string zpp01FamField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string BundlingWorkCenter
        {
            get
            {
                return this.bundlingWorkCenterField;
            }
            set
            {
                this.bundlingWorkCenterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string MaterialNumber
        {
            get
            {
                return this.materialNumberField;
            }
            set
            {
                this.materialNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public decimal PlannedQuantity
        {
            get
            {
                return this.plannedQuantityField;
            }
            set
            {
                this.plannedQuantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string FinishDate
        {
            get
            {
                return this.finishDateField;
            }
            set
            {
                this.finishDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string SlitCoil
        {
            get
            {
                return this.slitCoilField;
            }
            set
            {
                this.slitCoilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public decimal ReceivedQuantity
        {
            get
            {
                return this.receivedQuantityField;
            }
            set
            {
                this.receivedQuantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string Family
        {
            get
            {
                return this.familyField;
            }
            set
            {
                this.familyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string BlockNumber
        {
            get
            {
                return this.blockNumberField;
            }
            set
            {
                this.blockNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string BFixed
        {
            get
            {
                return this.bFixedField;
            }
            set
            {
                this.bFixedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public decimal Gauge
        {
            get
            {
                return this.gaugeField;
            }
            set
            {
                this.gaugeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public string GradeGroup
        {
            get
            {
                return this.gradeGroupField;
            }
            set
            {
                this.gradeGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public decimal CombFreeCap
        {
            get
            {
                return this.combFreeCapField;
            }
            set
            {
                this.combFreeCapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public decimal StockOrd
        {
            get
            {
                return this.stockOrdField;
            }
            set
            {
                this.stockOrdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public decimal StockReq
        {
            get
            {
                return this.stockReqField;
            }
            set
            {
                this.stockReqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
        public decimal BlkHrs
        {
            get
            {
                return this.blkHrsField;
            }
            set
            {
                this.blkHrsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
        public decimal StkordHrs
        {
            get
            {
                return this.stkordHrsField;
            }
            set
            {
                this.stkordHrsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 19)]
        public string StkLevel
        {
            get
            {
                return this.stkLevelField;
            }
            set
            {
                this.stkLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 20)]
        public decimal PlanHrs
        {
            get
            {
                return this.planHrsField;
            }
            set
            {
                this.planHrsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 21)]
        public decimal BookHrs
        {
            get
            {
                return this.bookHrsField;
            }
            set
            {
                this.bookHrsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 22)]
        public string Zpp01Fam
        {
            get
            {
                return this.zpp01FamField;
            }
            set
            {
                this.zpp01FamField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_PLANT
    {

        private string wERKSField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string WERKS
        {
            get
            {
                return this.wERKSField;
            }
            set
            {
                this.wERKSField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZatesSlitPatt
    {

        private string primSlitCoilField;

        private string plantField;

        private string priorityField;

        private string masterCoilField;

        private string numberOfCutsField;

        private string dropFamilyField;

        private decimal dropFamilyGaugField;

        private string cutsOnDropField;

        private string slabIndField;

        private string slabGrpIndField;

        private string groupDescField;

        private string optimizerFamilyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string PrimSlitCoil
        {
            get
            {
                return this.primSlitCoilField;
            }
            set
            {
                this.primSlitCoilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string MasterCoil
        {
            get
            {
                return this.masterCoilField;
            }
            set
            {
                this.masterCoilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string NumberOfCuts
        {
            get
            {
                return this.numberOfCutsField;
            }
            set
            {
                this.numberOfCutsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string DropFamily
        {
            get
            {
                return this.dropFamilyField;
            }
            set
            {
                this.dropFamilyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public decimal DropFamilyGaug
        {
            get
            {
                return this.dropFamilyGaugField;
            }
            set
            {
                this.dropFamilyGaugField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string CutsOnDrop
        {
            get
            {
                return this.cutsOnDropField;
            }
            set
            {
                this.cutsOnDropField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string SlabInd
        {
            get
            {
                return this.slabIndField;
            }
            set
            {
                this.slabIndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string SlabGrpInd
        {
            get
            {
                return this.slabGrpIndField;
            }
            set
            {
                this.slabGrpIndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string GroupDesc
        {
            get
            {
                return this.groupDescField;
            }
            set
            {
                this.groupDescField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string OptimizerFamily
        {
            get
            {
                return this.optimizerFamilyField;
            }
            set
            {
                this.optimizerFamilyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmGetSosapoSlitPatternResponse
    {

        private ZatesSlitPatt[] etSosapoSlitPatternField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ZatesSlitPatt[] EtSosapoSlitPattern
        {
            get
            {
                return this.etSosapoSlitPatternField;
            }
            set
            {
                this.etSosapoSlitPatternField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ZfmGetSosapoSlitPatternRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style", Order = 0)]
        public HSSPortalAPOSlitter.ZfmGetSosapoSlitPattern ZfmGetSosapoSlitPattern;

        public ZfmGetSosapoSlitPatternRequest()
        {
        }

        public ZfmGetSosapoSlitPatternRequest(HSSPortalAPOSlitter.ZfmGetSosapoSlitPattern ZfmGetSosapoSlitPattern)
        {
            this.ZfmGetSosapoSlitPattern = ZfmGetSosapoSlitPattern;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ZfmGetSosapoSlitPatternResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style", Order = 0)]
        public HSSPortalAPOSlitter.ZfmGetSosapoSlitPatternResponse ZfmGetSosapoSlitPatternResponse;

        public ZfmGetSosapoSlitPatternResponse1()
        {
        }

        public ZfmGetSosapoSlitPatternResponse1(HSSPortalAPOSlitter.ZfmGetSosapoSlitPatternResponse ZfmGetSosapoSlitPatternResponse)
        {
            this.ZfmGetSosapoSlitPatternResponse = ZfmGetSosapoSlitPatternResponse;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmGetSosapoTandemSchedule
    {

        private ZST_PLANT[] itPlantField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ZST_PLANT[] ItPlant
        {
            get
            {
                return this.itPlantField;
            }
            set
            {
                this.itPlantField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmGetSosapoTandemScheduleResponse
    {

        private ZatasSosTandemSchedule[] etSosapoTandemScheduleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ZatasSosTandemSchedule[] EtSosapoTandemSchedule
        {
            get
            {
                return this.etSosapoTandemScheduleField;
            }
            set
            {
                this.etSosapoTandemScheduleField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ZfmGetSosapoTandemScheduleRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style", Order = 0)]
        public HSSPortalAPOSlitter.ZfmGetSosapoTandemSchedule ZfmGetSosapoTandemSchedule;

        public ZfmGetSosapoTandemScheduleRequest()
        {
        }

        public ZfmGetSosapoTandemScheduleRequest(HSSPortalAPOSlitter.ZfmGetSosapoTandemSchedule ZfmGetSosapoTandemSchedule)
        {
            this.ZfmGetSosapoTandemSchedule = ZfmGetSosapoTandemSchedule;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ZfmGetSosapoTandemScheduleResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style", Order = 0)]
        public HSSPortalAPOSlitter.ZfmGetSosapoTandemScheduleResponse ZfmGetSosapoTandemScheduleResponse;

        public ZfmGetSosapoTandemScheduleResponse1()
        {
        }

        public ZfmGetSosapoTandemScheduleResponse1(HSSPortalAPOSlitter.ZfmGetSosapoTandemScheduleResponse ZfmGetSosapoTandemScheduleResponse)
        {
            this.ZfmGetSosapoTandemScheduleResponse = ZfmGetSosapoTandemScheduleResponse;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmPlanningProductExtract
    {

        private ZST_PLANT[] itPlantField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ZST_PLANT[] ItPlant
        {
            get
            {
                return this.itPlantField;
            }
            set
            {
                this.itPlantField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmPlanningProductExtractResponse
    {

        private Zplanningproduct[] etPlanningprodField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public Zplanningproduct[] EtPlanningprod
        {
            get
            {
                return this.etPlanningprodField;
            }
            set
            {
                this.etPlanningprodField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ZfmPlanningProductExtractRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style", Order = 0)]
        public HSSPortalAPOSlitter.ZfmPlanningProductExtract ZfmPlanningProductExtract;

        public ZfmPlanningProductExtractRequest()
        {
        }

        public ZfmPlanningProductExtractRequest(HSSPortalAPOSlitter.ZfmPlanningProductExtract ZfmPlanningProductExtract)
        {
            this.ZfmPlanningProductExtract = ZfmPlanningProductExtract;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ZfmPlanningProductExtractResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:sap-com:document:sap:soap:functions:mc-style", Order = 0)]
        public HSSPortalAPOSlitter.ZfmPlanningProductExtractResponse ZfmPlanningProductExtractResponse;

        public ZfmPlanningProductExtractResponse1()
        {
        }

        public ZfmPlanningProductExtractResponse1(HSSPortalAPOSlitter.ZfmPlanningProductExtractResponse ZfmPlanningProductExtractResponse)
        {
            this.ZfmPlanningProductExtractResponse = ZfmPlanningProductExtractResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ZWS_HSS_PORTAL_APO_SLITTERChannel : HSSPortalAPOSlitter.ZWS_HSS_PORTAL_APO_SLITTER, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ZWS_HSS_PORTAL_APO_SLITTERClient : System.ServiceModel.ClientBase<HSSPortalAPOSlitter.ZWS_HSS_PORTAL_APO_SLITTER>, HSSPortalAPOSlitter.ZWS_HSS_PORTAL_APO_SLITTER
    {
        public ZWS_HSS_PORTAL_APO_SLITTERClient()
        {
        }

        public ZWS_HSS_PORTAL_APO_SLITTERClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ZWS_HSS_PORTAL_APO_SLITTERClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSSPortalAPOSlitter.ZfmGetSosapoSlitPatternResponse HSSPortalAPOSlitter.ZWS_HSS_PORTAL_APO_SLITTER.ZfmGetSosapoSlitPatternAsync(HSSPortalAPOSlitter.ZfmGetSosapoSlitPatternRequest request)
        {
            return base.Channel.ZfmGetSosapoSlitPatternAsync(request);
        }

        public HSSPortalAPOSlitter.ZfmGetSosapoSlitPatternResponse ZfmGetSosapoSlitPatternAsync(HSSPortalAPOSlitter.ZfmGetSosapoSlitPattern ZfmGetSosapoSlitPattern)
        {
            HSSPortalAPOSlitter.ZfmGetSosapoSlitPatternRequest inValue = new HSSPortalAPOSlitter.ZfmGetSosapoSlitPatternRequest();
            inValue.ZfmGetSosapoSlitPattern = ZfmGetSosapoSlitPattern;
            return ((HSSPortalAPOSlitter.ZWS_HSS_PORTAL_APO_SLITTER)(this)).ZfmGetSosapoSlitPatternAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSSPortalAPOSlitter.ZfmGetSosapoTandemScheduleResponse HSSPortalAPOSlitter.ZWS_HSS_PORTAL_APO_SLITTER.ZfmGetSosapoTandemScheduleAsync(HSSPortalAPOSlitter.ZfmGetSosapoTandemScheduleRequest request)
        {
            return base.Channel.ZfmGetSosapoTandemScheduleAsync(request);
        }

        public HSSPortalAPOSlitter.ZfmGetSosapoTandemScheduleResponse ZfmGetSosapoTandemScheduleAsync(HSSPortalAPOSlitter.ZfmGetSosapoTandemSchedule ZfmGetSosapoTandemSchedule)
        {
            HSSPortalAPOSlitter.ZfmGetSosapoTandemScheduleRequest inValue = new HSSPortalAPOSlitter.ZfmGetSosapoTandemScheduleRequest();
            inValue.ZfmGetSosapoTandemSchedule = ZfmGetSosapoTandemSchedule;
            return ((HSSPortalAPOSlitter.ZWS_HSS_PORTAL_APO_SLITTER)(this)).ZfmGetSosapoTandemScheduleAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSSPortalAPOSlitter.ZfmPlanningProductExtractResponse HSSPortalAPOSlitter.ZWS_HSS_PORTAL_APO_SLITTER.ZfmPlanningProductExtractAsync(HSSPortalAPOSlitter.ZfmPlanningProductExtractRequest request)
        {
            return base.Channel.ZfmPlanningProductExtractAsync(request);
        }

        public HSSPortalAPOSlitter.ZfmPlanningProductExtractResponse ZfmPlanningProductExtractAsync(HSSPortalAPOSlitter.ZfmPlanningProductExtract ZfmPlanningProductExtract)
        {
            HSSPortalAPOSlitter.ZfmPlanningProductExtractRequest inValue = new HSSPortalAPOSlitter.ZfmPlanningProductExtractRequest();
            inValue.ZfmPlanningProductExtract = ZfmPlanningProductExtract;
            return ((HSSPortalAPOSlitter.ZWS_HSS_PORTAL_APO_SLITTER)(this)).ZfmPlanningProductExtractAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
