// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Keyless]
    [Table("AlternateSoldTo")]
    [Microsoft.EntityFrameworkCore.Index(nameof(SapshipToId), nameof(AlternateSapsoldToId), Name = "IX_AlternateSoldTo", IsUnique = true)]
    public partial class AlternateSoldTo
    {
        [Column("SAPShipToID")]
        public long SapshipToId { get; set; }
        [Column("AlternateSAPSoldToID")]
        public long AlternateSapsoldToId { get; set; }

        [ForeignKey(nameof(AlternateSapsoldToId))]
        public virtual SapsoldTo AlternateSapsoldTo { get; set; }
        [ForeignKey(nameof(SapshipToId))]
        public virtual SapsoldTo SapshipTo { get; set; }
    }
}