// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("Application")]
    public partial class Application
    {
        public Application()
        {
            ApplicationRoles = new HashSet<ApplicationRole>();
            UserProfiles = new HashSet<UserProfile>();
        }

        [Key]
        [Column("ApplicationID")]
        public long ApplicationId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column("URL")]
        [StringLength(255)]
        public string Url { get; set; }
        [StringLength(50)]
        public string LongName { get; set; }

        [InverseProperty(nameof(ApplicationRole.Application))]
        public virtual ICollection<ApplicationRole> ApplicationRoles { get; set; }
        [InverseProperty(nameof(UserProfile.Application))]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}