// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ApplicationRole")]
    public partial class ApplicationRole
    {
        [Key]
        [Column("ApplicationRoleID")]
        public long ApplicationRoleId { get; set; }
        [Column("ApplicationID")]
        public long ApplicationId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [ForeignKey(nameof(ApplicationId))]
        [InverseProperty("ApplicationRoles")]
        public virtual Application Application { get; set; }
    }
}