// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Keyless]
    [Table("ATPEmployeePlant")]
    [Microsoft.EntityFrameworkCore.Index(nameof(UserId), nameof(LocationId), Name = "IX_ATPEmployeePlant", IsUnique = true)]
    public partial class AtpemployeePlant
    {
        [Column("UserID")]
        public long UserId { get; set; }
        [Column("LocationID")]
        public long LocationId { get; set; }

        [ForeignKey(nameof(LocationId))]
        public virtual Plant Location { get; set; }
        [ForeignKey(nameof(UserId))]
        public virtual Employee User { get; set; }
    }
}