// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("City")]
    [Microsoft.EntityFrameworkCore.Index(nameof(Name), nameof(StateId), Name = "IX_City", IsUnique = true)]
    public partial class City
    {
        public City()
        {
            Locations = new HashSet<Location>();
            SapshipTos = new HashSet<SapshipTo>();
            Sapvendors = new HashSet<Sapvendor>();
        }

        [Key]
        [Column("CityID")]
        public long CityId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("StateID")]
        public long StateId { get; set; }
        [Required]
        public bool? Active { get; set; }
        public int? TimeZoneId { get; set; }

        [ForeignKey(nameof(StateId))]
        [InverseProperty("Cities")]
        public virtual State State { get; set; }
        [InverseProperty(nameof(Location.City))]
        public virtual ICollection<Location> Locations { get; set; }
        [InverseProperty(nameof(SapshipTo.City))]
        public virtual ICollection<SapshipTo> SapshipTos { get; set; }
        [InverseProperty(nameof(Sapvendor.City))]
        public virtual ICollection<Sapvendor> Sapvendors { get; set; }
    }
}