// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Keyless]
    [Table("ClaimRequest")]
    public partial class ClaimRequest
    {
        [Column(TypeName = "date")]
        public DateTime? RequestDate { get; set; }
        [StringLength(50)]
        public string SoldTo { get; set; }
        [StringLength(50)]
        public string ShipTo { get; set; }
        [Column("ISR")]
        [StringLength(50)]
        public string Isr { get; set; }
        [StringLength(50)]
        public string BillOfLading { get; set; }
        [StringLength(10)]
        public string Contact { get; set; }
        [StringLength(10)]
        public string ContactNo { get; set; }
        public int PiecesAffected { get; set; }
        [StringLength(50)]
        public string MigrationsOptions { get; set; }
        [StringLength(10)]
        public string MaterialLength { get; set; }
        [StringLength(10)]
        public string MaterialGauge { get; set; }
        [StringLength(10)]
        public string MaterialSize { get; set; }
        [StringLength(50)]
        public string BatchNos { get; set; }
        [StringLength(50)]
        public string Reason { get; set; }
    }
}