// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("CMIR")]
    public partial class Cmir
    {
        [Key]
        [Column("CMIRID")]
        public long Cmirid { get; set; }
        [Column("SAPSalesOrganizationID")]
        public long SapsalesOrganizationId { get; set; }
        [StringLength(10)]
        public string DistributionChannel { get; set; }
        [Column("SAPShipToID")]
        public long SapshipToId { get; set; }
        [Column("SAPMaterialID")]
        public long SapmaterialId { get; set; }
        [StringLength(50)]
        public string CustomerPartNumber { get; set; }

        [ForeignKey(nameof(SapmaterialId))]
        [InverseProperty("Cmirs")]
        public virtual Sapmaterial Sapmaterial { get; set; }
        [ForeignKey(nameof(SapsalesOrganizationId))]
        [InverseProperty("Cmirs")]
        public virtual SapsalesOrganization SapsalesOrganization { get; set; }
        [ForeignKey(nameof(SapshipToId))]
        [InverseProperty(nameof(SapsoldTo.Cmirs))]
        public virtual SapsoldTo SapshipTo { get; set; }
    }
}