// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("Country")]
    [Microsoft.EntityFrameworkCore.Index(nameof(Name), nameof(Abbreviation), Name = "IX_Country", IsUnique = true)]
    public partial class Country
    {
        public Country()
        {
            States = new HashSet<State>();
        }

        [Key]
        [Column("CountryID")]
        public long CountryId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(3)]
        public string Abbreviation { get; set; }
        [Required]
        public bool? Active { get; set; }

        [InverseProperty(nameof(State.Country))]
        public virtual ICollection<State> States { get; set; }
    }
}