// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("DataView")]
    public partial class DataView
    {
        public DataView()
        {
            DataViewColumns = new HashSet<DataViewColumn>();
            PersonDataViewTemplates = new HashSet<PersonDataViewTemplate>();
        }

        [Key]
        [Column("DataViewID")]
        public long DataViewId { get; set; }
        [Required]
        [StringLength(150)]
        public string Name { get; set; }

        [InverseProperty(nameof(DataViewColumn.DataView))]
        public virtual ICollection<DataViewColumn> DataViewColumns { get; set; }
        [InverseProperty(nameof(PersonDataViewTemplate.DataView))]
        public virtual ICollection<PersonDataViewTemplate> PersonDataViewTemplates { get; set; }
    }
}