// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("DealsBySoldToShipTo")]
    public partial class DealsBySoldToShipTo
    {
        [Column("SAPSoldToID")]
        public long? SapsoldToId { get; set; }
        [Column("SAPShipToID")]
        public long? SapshipToId { get; set; }
        [Column("DealID")]
        public long DealId { get; set; }
        [Key]
        [Column("ID")]
        public long Id { get; set; }

        [ForeignKey(nameof(DealId))]
        [InverseProperty(nameof(DealsDetail.DealsBySoldToShipTos))]
        public virtual DealsDetail Deal { get; set; }
        [ForeignKey(nameof(SapshipToId))]
        [InverseProperty("DealsBySoldToShipTos")]
        public virtual SapshipTo SapshipTo { get; set; }
        [ForeignKey(nameof(SapsoldToId))]
        [InverseProperty("DealsBySoldToShipTos")]
        public virtual SapsoldTo SapsoldTo { get; set; }
    }
}