// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    public partial class DealsMaterialPricingGroup
    {
        [Column("DealID")]
        public long? DealId { get; set; }
        [Column("ZR00")]
        public long? Zr00 { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Discount { get; set; }
        [Key]
        [Column("DealsMaterialPricingGroupsID")]
        public long DealsMaterialPricingGroupsId { get; set; }

        [ForeignKey(nameof(DealId))]
        [InverseProperty(nameof(DealsDetail.DealsMaterialPricingGroups))]
        public virtual DealsDetail Deal { get; set; }
        [ForeignKey(nameof(Zr00))]
        [InverseProperty(nameof(SapcharacteristicOption.DealsMaterialPricingGroups))]
        public virtual SapcharacteristicOption Zr00Navigation { get; set; }
    }
}