// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    public partial class DealsPricingGroup
    {
        [Column("ZR01")]
        public long? Zr01 { get; set; }
        [Column("DealID")]
        public long? DealId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Discount { get; set; }
        [Key]
        [Column("DealsPricingGroupsID")]
        public long DealsPricingGroupsId { get; set; }

        [ForeignKey(nameof(DealId))]
        [InverseProperty(nameof(DealsDetail.DealsPricingGroups))]
        public virtual DealsDetail Deal { get; set; }
        [ForeignKey(nameof(Zr01))]
        [InverseProperty(nameof(SapcharacteristicOption.DealsPricingGroups))]
        public virtual SapcharacteristicOption Zr01Navigation { get; set; }
    }
}