// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("DealsPlant")]
    public partial class DealsPlant
    {
        [Key]
        [Column("ID")]
        public long Id { get; set; }
        [Column("PlantID")]
        public long? PlantId { get; set; }
        [Column("DealID")]
        public long? DealId { get; set; }

        [ForeignKey(nameof(DealId))]
        [InverseProperty(nameof(DealsDetail.DealsPlants))]
        public virtual DealsDetail Deal { get; set; }
    }
}