// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    public partial class DealsDetail
    {
        public DealsDetail()
        {
            DealsBySoldToShipTos = new HashSet<DealsBySoldToShipTo>();
            DealsMaterialPricingGroups = new HashSet<DealsMaterialPricingGroup>();
            DealsPlants = new HashSet<DealsPlant>();
            DealsPricingGroups = new HashSet<DealsPricingGroup>();
        }

        [StringLength(50)]
        public string Name { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OrderFromDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OrderToDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ShipFromDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ShipToDate { get; set; }
        public long? ThresholdLimit { get; set; }
        public bool? ApprovedDenied { get; set; }
        public bool? InActive { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string ApprovedBy { get; set; }
        [StringLength(50)]
        public string DealType { get; set; }
        [Key]
        [Column("DealID")]
        public long DealId { get; set; }
        [Column("CreatedUserID")]
        public long? CreatedUserId { get; set; }
        [Column("ApprovedUserID")]
        public long? ApprovedUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ApprovedDeniedDate { get; set; }
        [StringLength(2000)]
        public string Notes { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? TonsUsed { get; set; }
        public long? FirmFlag { get; set; }
        public long? MaxTons { get; set; }

        [InverseProperty(nameof(DealsBySoldToShipTo.Deal))]
        public virtual ICollection<DealsBySoldToShipTo> DealsBySoldToShipTos { get; set; }
        [InverseProperty(nameof(DealsMaterialPricingGroup.Deal))]
        public virtual ICollection<DealsMaterialPricingGroup> DealsMaterialPricingGroups { get; set; }
        [InverseProperty(nameof(DealsPlant.Deal))]
        public virtual ICollection<DealsPlant> DealsPlants { get; set; }
        [InverseProperty(nameof(DealsPricingGroup.Deal))]
        public virtual ICollection<DealsPricingGroup> DealsPricingGroups { get; set; }
    }
}