// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("DeliveryMethod")]
    public partial class DeliveryMethod
    {
        public DeliveryMethod()
        {
            Sapshipments = new HashSet<Sapshipment>();
        }

        [Key]
        [Column("DeliveryMethodID")]
        public long DeliveryMethodId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty(nameof(Sapshipment.DeliveryMethod))]
        public virtual ICollection<Sapshipment> Sapshipments { get; set; }
    }
}