// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("Department")]
    public partial class Department
    {
        public Department()
        {
            Employees = new HashSet<Employee>();
            PlantComputers = new HashSet<PlantComputer>();
        }

        [Key]
        [Column("DepartmentID")]
        public long DepartmentId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column("ADName")]
        [StringLength(50)]
        public string Adname { get; set; }

        [InverseProperty(nameof(Employee.Department))]
        public virtual ICollection<Employee> Employees { get; set; }
        [InverseProperty(nameof(PlantComputer.Department))]
        public virtual ICollection<PlantComputer> PlantComputers { get; set; }
    }
}