// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("Division")]
    public partial class Division
    {
        public Division()
        {
            Employees = new HashSet<Employee>();
            Locations = new HashSet<Location>();
            PendingShipmentCosts = new HashSet<PendingShipmentCost>();
            PriceChangeRequests = new HashSet<PriceChangeRequest>();
            ProductLines = new HashSet<ProductLine>();
            Quotes = new HashSet<Quote>();
            SapbundlingOptions = new HashSet<SapbundlingOption>();
            SapcharacteristicTypes = new HashSet<SapcharacteristicType>();
            SapconditionGroups = new HashSet<SapconditionGroup>();
            Sapconditions = new HashSet<Sapcondition>();
            SapcustomerGroups = new HashSet<SapcustomerGroup>();
            SapcustomerServiceReps = new HashSet<SapcustomerServiceRep>();
            Sapdeliveries = new HashSet<Sapdelivery>();
            Sapmaterials = new HashSet<Sapmaterial>();
            Sapregions = new HashSet<Sapregion>();
            SapsalesGroups = new HashSet<SapsalesGroup>();
            SapsalesOrders = new HashSet<SapsalesOrder>();
            SapsalesOrganizations = new HashSet<SapsalesOrganization>();
            SapshipTos = new HashSet<SapshipTo>();
            Sapshipments = new HashSet<Sapshipment>();
            Saptiers = new HashSet<Saptier>();
            Sapvendors = new HashSet<Sapvendor>();
            ScrapSales = new HashSet<ScrapSale>();
        }

        [Key]
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty(nameof(Employee.Division))]
        public virtual ICollection<Employee> Employees { get; set; }
        [InverseProperty(nameof(Location.Division))]
        public virtual ICollection<Location> Locations { get; set; }
        [InverseProperty(nameof(PendingShipmentCost.Division))]
        public virtual ICollection<PendingShipmentCost> PendingShipmentCosts { get; set; }
        [InverseProperty(nameof(PriceChangeRequest.Division))]
        public virtual ICollection<PriceChangeRequest> PriceChangeRequests { get; set; }
        [InverseProperty(nameof(ProductLine.Division))]
        public virtual ICollection<ProductLine> ProductLines { get; set; }
        [InverseProperty(nameof(Quote.Division))]
        public virtual ICollection<Quote> Quotes { get; set; }
        [InverseProperty(nameof(SapbundlingOption.Division))]
        public virtual ICollection<SapbundlingOption> SapbundlingOptions { get; set; }
        [InverseProperty(nameof(SapcharacteristicType.Division))]
        public virtual ICollection<SapcharacteristicType> SapcharacteristicTypes { get; set; }
        [InverseProperty(nameof(SapconditionGroup.Division))]
        public virtual ICollection<SapconditionGroup> SapconditionGroups { get; set; }
        [InverseProperty(nameof(Sapcondition.Division))]
        public virtual ICollection<Sapcondition> Sapconditions { get; set; }
        [InverseProperty(nameof(SapcustomerGroup.Division))]
        public virtual ICollection<SapcustomerGroup> SapcustomerGroups { get; set; }
        [InverseProperty(nameof(SapcustomerServiceRep.Division))]
        public virtual ICollection<SapcustomerServiceRep> SapcustomerServiceReps { get; set; }
        [InverseProperty(nameof(Sapdelivery.Division))]
        public virtual ICollection<Sapdelivery> Sapdeliveries { get; set; }
        [InverseProperty(nameof(Sapmaterial.Division))]
        public virtual ICollection<Sapmaterial> Sapmaterials { get; set; }
        [InverseProperty(nameof(Sapregion.Division))]
        public virtual ICollection<Sapregion> Sapregions { get; set; }
        [InverseProperty(nameof(SapsalesGroup.Division))]
        public virtual ICollection<SapsalesGroup> SapsalesGroups { get; set; }
        [InverseProperty(nameof(SapsalesOrder.Division))]
        public virtual ICollection<SapsalesOrder> SapsalesOrders { get; set; }
        [InverseProperty(nameof(SapsalesOrganization.Division))]
        public virtual ICollection<SapsalesOrganization> SapsalesOrganizations { get; set; }
        [InverseProperty(nameof(SapshipTo.Division))]
        public virtual ICollection<SapshipTo> SapshipTos { get; set; }
        [InverseProperty(nameof(Sapshipment.Division))]
        public virtual ICollection<Sapshipment> Sapshipments { get; set; }
        [InverseProperty(nameof(Saptier.Division))]
        public virtual ICollection<Saptier> Saptiers { get; set; }
        [InverseProperty(nameof(Sapvendor.Division))]
        public virtual ICollection<Sapvendor> Sapvendors { get; set; }
        [InverseProperty(nameof(ScrapSale.Division))]
        public virtual ICollection<ScrapSale> ScrapSales { get; set; }
    }
}