// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("Employee")]
    public partial class Employee
    {
        public Employee()
        {
            Quotes = new HashSet<Quote>();
        }

        [Key]
        [Column("UserID")]
        public long UserId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Column("EmployeePositionID")]
        public long? EmployeePositionId { get; set; }
        [Column("LocationID")]
        public long? LocationId { get; set; }
        [Column("DepartmentID")]
        public long? DepartmentId { get; set; }
        [Column("SAMAccountName")]
        [StringLength(50)]
        public string SamaccountName { get; set; }
        [StringLength(15)]
        public string Domain { get; set; }
        [Column("ManagerID")]
        public int? ManagerId { get; set; }

        [ForeignKey(nameof(DepartmentId))]
        [InverseProperty("Employees")]
        public virtual Department Department { get; set; }
        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("Employees")]
        public virtual Division Division { get; set; }
        [ForeignKey(nameof(EmployeePositionId))]
        [InverseProperty("Employees")]
        public virtual EmployeePosition EmployeePosition { get; set; }
        [ForeignKey(nameof(LocationId))]
        [InverseProperty("Employees")]
        public virtual Location Location { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("Employee")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(Quote.Employee))]
        public virtual ICollection<Quote> Quotes { get; set; }





        public virtual ICollection<ApplicationRole> ApplicationRoles { get; set; }
    }
}