// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("FiscalPeriod")]
    public partial class FiscalPeriod
    {
        [Key]
        [Column("FiscalPeriodID")]
        public long FiscalPeriodId { get; set; }
        [Column("FiscalYearID")]
        public long FiscalYearId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EndDate { get; set; }
        public int PeriodNumber { get; set; }

        [ForeignKey(nameof(FiscalYearId))]
        [InverseProperty("FiscalPeriods")]
        public virtual FiscalYear FiscalYear { get; set; }
    }
}