// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("FiscalYear")]
    public partial class FiscalYear
    {
        public FiscalYear()
        {
            FiscalPeriods = new HashSet<FiscalPeriod>();
        }

        [Key]
        [Column("FiscalYearID")]
        public long FiscalYearId { get; set; }
        public int TheFiscalYear { get; set; }

        [InverseProperty(nameof(FiscalPeriod.FiscalYear))]
        public virtual ICollection<FiscalPeriod> FiscalPeriods { get; set; }
    }
}