// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace JMC.Portal.Business.PortalModels
{
    public partial class FixFKConstraintsResult
    {
        public int? FKID { get; set; }
        public string TableName { get; set; }
        public string FKName { get; set; }
        public string SQL { get; set; }
    }
}
