// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("FreightandFSC")]
    public partial class FreightandFsc
    {
        [Key]
        [Column("freightID")]
        public long FreightId { get; set; }
        [Column("SAPShiptoID")]
        public long SapshiptoId { get; set; }
        [Column("SAPConditionID")]
        public long SapconditionId { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal Rate { get; set; }
        [Required]
        [StringLength(10)]
        public string Currency { get; set; }
        public long Per { get; set; }
        [Required]
        [StringLength(10)]
        public string Unit { get; set; }
        [Column(TypeName = "date")]
        public DateTime ValidFrom { get; set; }
        [Column(TypeName = "date")]
        public DateTime ValidTo { get; set; }
        public bool RegionalFreight { get; set; }
        [Column("SAPSoldtoID")]
        public long? SapsoldtoId { get; set; }

        [ForeignKey(nameof(SapconditionId))]
        [InverseProperty("FreightandFscs")]
        public virtual Sapcondition Sapcondition { get; set; }
        [ForeignKey(nameof(SapshiptoId))]
        [InverseProperty(nameof(SapshipTo.FreightandFscs))]
        public virtual SapshipTo Sapshipto { get; set; }
    }
}