// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("Gauge")]
    public partial class Gauge
    {
        [Key]
        [Column("GaugeID")]
        public int GaugeId { get; set; }
        [Column("Gauge", TypeName = "decimal(9, 3)")]
        public decimal Gauge1 { get; set; }
        [Required]
        [StringLength(50)]
        public string MaterialGroup { get; set; }
        [Column("NPS")]
        public bool? Nps { get; set; }
        [Column("NPSDescription")]
        [StringLength(50)]
        public string Npsdescription { get; set; }
    }
}