// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace JMC.Portal.Business.PortalModels
{
    public partial class GetBacklogResult
    {
        public long? SAPSoldToID { get; set; }
        public string SAPSoldToNumber { get; set; }
        public string SAPSoldToName { get; set; }
        public long? SAPShipToID { get; set; }
        public string SAPShipToNumber { get; set; }
        public string SAPShipToName { get; set; }
        public string SAPShipToIncoTerms2 { get; set; }
        public long? PlantID { get; set; }
        public string PlantName { get; set; }
        public decimal? DisplayNotReadyWeight { get; set; }
        public decimal? DisplayReadyWeight { get; set; }
        public decimal? DisplayReleasedWeight { get; set; }
        public decimal? DeliveryWeight { get; set; }
    }
}
