// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace JMC.Portal.Business.PortalModels
{
    public partial class GetSAPStockResult
    {
        public long SAPStockID { get; set; }
        public string Name { get; set; }
        public decimal Weight { get; set; }
        public long PlantID { get; set; }
        public decimal? Size { get; set; }
        public decimal? Size2 { get; set; }
        public decimal? Diameter { get; set; }
        public decimal? GaugeRestrictable { get; set; }
        public string PlantDisplayName { get; set; }
        public string Grade { get; set; }
        public decimal? ConsumedInShoppingCartPieces { get; set; }
        public string Status { get; set; }
        public decimal? WeightPerPiece { get; set; }
        public int? PiecesPerBundle { get; set; }
        public int AvailablePieces { get; set; }
        public int? Remainder { get; set; }
        public decimal TubeLength { get; set; }
        public int? MaxStockLevel { get; set; }
        public DateTime? RollingEndDate { get; set; }
        public int? CloseRollingPcs { get; set; }
        public decimal? CloseRollingWeight { get; set; }
    }
}
