// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace JMC.Portal.Business.PortalModels
{
    public partial class GetSAPMaterialPricingResult
    {
        public long? SAPMaterialID { get; set; }
        public long ShipTo { get; set; }
        public decimal? ZR00Rate { get; set; }
        public string ZR00Currency { get; set; }
        public long? ZR00Per { get; set; }
        public string ZR00Unit { get; set; }
        public decimal? ZR01Rate { get; set; }
        public string ZR01Currency { get; set; }
        public long? ZR01Per { get; set; }
        public string ZR01Unit { get; set; }
        public decimal? ZR04Rate { get; set; }
        public string ZR04Currency { get; set; }
        public long? ZR04Per { get; set; }
        public string ZR04Unit { get; set; }
        public decimal? ZEP1Rate { get; set; }
        public string ZEP1Currency { get; set; }
        public long? ZEP1Per { get; set; }
        public string ZEP1Unit { get; set; }
        public decimal? ZG01Rate { get; set; }
        public string ZG01Currency { get; set; }
        public long? ZG01Per { get; set; }
        public string ZG01Unit { get; set; }
        public decimal? FCSRate { get; set; }
        public string FCSCurrency { get; set; }
        public long? FCSPer { get; set; }
        public string FCSUnit { get; set; }
    }
}
