// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("IPSFile")]
    public partial class Ipsfile
    {
        [Key]
        [Column("IPSFileID")]
        public long IpsfileId { get; set; }
        [Column("UserID")]
        public long UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("Ipsfiles")]
        public virtual User User { get; set; }
    }
}