// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("LoginHistory")]
    [Microsoft.EntityFrameworkCore.Index(nameof(LoginDate), Name = "ix_LoginDate")]
    [Microsoft.EntityFrameworkCore.Index(nameof(UserId), nameof(LoginDate), Name = "ix_UserID_LoginDate")]
    public partial class LoginHistory
    {
        [Key]
        [Column("LoginHistoryID")]
        public long LoginHistoryId { get; set; }
        [Column("UserID")]
        public long UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LoginDate { get; set; }
        [StringLength(500)]
        public string UserAgent { get; set; }
        [StringLength(50)]
        public string BrowserName { get; set; }
        [StringLength(50)]
        public string BrowserVersion { get; set; }
        public bool? Cookies { get; set; }
        public bool? Javascript { get; set; }
        [StringLength(50)]
        public string Platform { get; set; }
        [StringLength(50)]
        public string ScreenResolution { get; set; }
        [StringLength(50)]
        public string IpAddress { get; set; }
        [StringLength(50)]
        public string HostName { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("LoginHistories")]
        public virtual User User { get; set; }
    }
}