// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("PendingShipmentCost")]
    public partial class PendingShipmentCost
    {
        [Key]
        [Column("PendingShipmentCostID")]
        public long PendingShipmentCostId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Column("ShipmentCostTypeID")]
        public long ShipmentCostTypeId { get; set; }
        [Required]
        [Column("BOL")]
        [StringLength(50)]
        public string Bol { get; set; }
        [Required]
        [StringLength(1)]
        public string BalanceDueSupplemental { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal Amount { get; set; }

        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("PendingShipmentCosts")]
        public virtual Division Division { get; set; }
        [ForeignKey(nameof(ShipmentCostTypeId))]
        [InverseProperty("PendingShipmentCosts")]
        public virtual ShipmentCostType ShipmentCostType { get; set; }
    }
}