// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("PersonDataViewColumnTemplate")]
    public partial class PersonDataViewColumnTemplate
    {
        [Key]
        [Column("PersonDataViewColumnTemplateID")]
        public long PersonDataViewColumnTemplateId { get; set; }
        [Column("PersonDataViewTemplateID")]
        public long PersonDataViewTemplateId { get; set; }
        [Column("DataViewColumnID")]
        public long DataViewColumnId { get; set; }
        public int Width { get; set; }
        public bool Visible { get; set; }
        public int Order { get; set; }
        [StringLength(4)]
        public string SortDirection { get; set; }
        public int? GroupByOrder { get; set; }
        [StringLength(4)]
        public string GroupByDirection { get; set; }
        [StringLength(50)]
        public string FirstFilter { get; set; }
        [StringLength(20)]
        public string FirstFilterOperator { get; set; }
        public string FirstFilterValue { get; set; }
        [StringLength(10)]
        public string Logic { get; set; }
        [StringLength(50)]
        public string SecondFilter { get; set; }
        [StringLength(20)]
        public string SecondFilterOperator { get; set; }
        public string SecondFilterValue { get; set; }

        [ForeignKey(nameof(DataViewColumnId))]
        [InverseProperty("PersonDataViewColumnTemplates")]
        public virtual DataViewColumn DataViewColumn { get; set; }
        [ForeignKey(nameof(PersonDataViewTemplateId))]
        [InverseProperty("PersonDataViewColumnTemplates")]
        public virtual PersonDataViewTemplate PersonDataViewTemplate { get; set; }
    }
}