// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("PersonDataViewTemplate")]
    public partial class PersonDataViewTemplate
    {
        public PersonDataViewTemplate()
        {
            PersonDataViewColumnTemplates = new HashSet<PersonDataViewColumnTemplate>();
        }

        [Key]
        [Column("PersonDataViewTemplateID")]
        public long PersonDataViewTemplateId { get; set; }
        [Column("PersonID")]
        public long PersonId { get; set; }
        [Column("DataViewID")]
        public long DataViewId { get; set; }

        [ForeignKey(nameof(DataViewId))]
        [InverseProperty("PersonDataViewTemplates")]
        public virtual DataView DataView { get; set; }
        [InverseProperty(nameof(PersonDataViewColumnTemplate.PersonDataViewTemplate))]
        public virtual ICollection<PersonDataViewColumnTemplate> PersonDataViewColumnTemplates { get; set; }
    }
}