// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("PhoneNumber")]
    public partial class PhoneNumber
    {
        [Key]
        [Column("PhoneNumberID")]
        public long PhoneNumberId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Number { get; set; }
        [Column("LocationID")]
        public long? LocationId { get; set; }

        [ForeignKey(nameof(LocationId))]
        [InverseProperty("PhoneNumbers")]
        public virtual Location Location { get; set; }
    }
}