// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("Plant")]
    public partial class Plant
    {
        public Plant()
        {
            Mills = new HashSet<Mill>();
            Quotes = new HashSet<Quote>();
            Rollings = new HashSet<Rolling>();
            Sapdeliveries = new HashSet<Sapdelivery>();
            SapmaterialPlants = new HashSet<SapmaterialPlant>();
            SapsalesOrderItems = new HashSet<SapsalesOrderItem>();
            SapsalesOrders = new HashSet<SapsalesOrder>();
            Sapshipments = new HashSet<Sapshipment>();
            SapsoldToPlantExclusions = new HashSet<SapsoldToPlantExclusion>();
            Sapstocks = new HashSet<Sapstock>();
            SapstorageLocations = new HashSet<SapstorageLocation>();
            ScrapSales = new HashSet<ScrapSale>();
            ShoppingCartSaprollings = new HashSet<ShoppingCartSaprolling>();
            Stocks = new HashSet<Stock>();
            WebReleasePlants = new HashSet<WebReleasePlant>();
        }

        [Key]
        [Column("LocationID")]
        public long LocationId { get; set; }
        [Required]
        [StringLength(4)]
        public string Code { get; set; }
        [Required]
        [StringLength(4)]
        public string SalesOrganization { get; set; }
        [Column("HomeMillSAPConditionGroupID")]
        public long? HomeMillSapconditionGroupId { get; set; }

        [ForeignKey(nameof(HomeMillSapconditionGroupId))]
        [InverseProperty(nameof(SapconditionGroup.Plants))]
        public virtual SapconditionGroup HomeMillSapconditionGroup { get; set; }
        [ForeignKey(nameof(LocationId))]
        [InverseProperty("Plant")]
        public virtual Location Location { get; set; }
        [InverseProperty(nameof(Mill.Plant))]
        public virtual ICollection<Mill> Mills { get; set; }
        [InverseProperty(nameof(Quote.ProductionPlant))]
        public virtual ICollection<Quote> Quotes { get; set; }
        [InverseProperty(nameof(Rolling.Plant))]
        public virtual ICollection<Rolling> Rollings { get; set; }
        [InverseProperty(nameof(Sapdelivery.Plant))]
        public virtual ICollection<Sapdelivery> Sapdeliveries { get; set; }
        [InverseProperty(nameof(SapmaterialPlant.Plant))]
        public virtual ICollection<SapmaterialPlant> SapmaterialPlants { get; set; }
        [InverseProperty(nameof(SapsalesOrderItem.Plant))]
        public virtual ICollection<SapsalesOrderItem> SapsalesOrderItems { get; set; }
        [InverseProperty(nameof(SapsalesOrder.Plant))]
        public virtual ICollection<SapsalesOrder> SapsalesOrders { get; set; }
        [InverseProperty(nameof(Sapshipment.Plant))]
        public virtual ICollection<Sapshipment> Sapshipments { get; set; }
        [InverseProperty(nameof(SapsoldToPlantExclusion.Plant))]
        public virtual ICollection<SapsoldToPlantExclusion> SapsoldToPlantExclusions { get; set; }
        [InverseProperty(nameof(Sapstock.Plant))]
        public virtual ICollection<Sapstock> Sapstocks { get; set; }
        [InverseProperty(nameof(SapstorageLocation.Plant))]
        public virtual ICollection<SapstorageLocation> SapstorageLocations { get; set; }
        [InverseProperty(nameof(ScrapSale.Plant))]
        public virtual ICollection<ScrapSale> ScrapSales { get; set; }
        [InverseProperty(nameof(ShoppingCartSaprolling.Plant))]
        public virtual ICollection<ShoppingCartSaprolling> ShoppingCartSaprollings { get; set; }
        [InverseProperty(nameof(Stock.Plant))]
        public virtual ICollection<Stock> Stocks { get; set; }
        [InverseProperty(nameof(WebReleasePlant.Plant))]
        public virtual ICollection<WebReleasePlant> WebReleasePlants { get; set; }
    }
}