// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("PlantComputer")]
    public partial class PlantComputer
    {
        [Key]
        [Column("UserID")]
        public long UserId { get; set; }
        [Required]
        [StringLength(50)]
        public string ComputerName { get; set; }
        [Column("LocationID")]
        public long LocationId { get; set; }
        [Column("DepartmentID")]
        public long? DepartmentId { get; set; }

        [ForeignKey(nameof(DepartmentId))]
        [InverseProperty("PlantComputers")]
        public virtual Department Department { get; set; }
        [ForeignKey(nameof(LocationId))]
        [InverseProperty("PlantComputers")]
        public virtual Location Location { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("PlantComputer")]
        public virtual User User { get; set; }
    }
}