// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace JMC.Portal.Business.PortalModels
{
    public partial class PortalUsageResult
    {
        public long? SAPSoldToID { get; set; }
        public string SoldToName { get; set; }
        public string SoldToNumber { get; set; }
        public decimal? TonsOrdered { get; set; }
        public decimal? TonsReleased { get; set; }
        public string UserName { get; set; }
        public long? UserId { get; set; }
    }
}
