// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("PriceChangeRequestItem")]
    public partial class PriceChangeRequestItem
    {
        [Key]
        [Column("PriceChangeRequestItemID")]
        public long PriceChangeRequestItemId { get; set; }
        [Column("PriceChangeRequestID")]
        public long PriceChangeRequestId { get; set; }
        [Column("SAPConditionID")]
        public long SapconditionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EffectiveDate { get; set; }
        [Column("SAPShipToID")]
        public long? SapshipToId { get; set; }
        [Column("SAPMaterialPricingGroupID")]
        public long? SapmaterialPricingGroupId { get; set; }
        [Column("SAPPricingGroupID")]
        public long? SappricingGroupId { get; set; }
        [Column("SAPMaterialGroupID")]
        public long? SapmaterialGroupId { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? Rate { get; set; }
        public bool? Approved { get; set; }
        [Column("ApprovedUserID")]
        public long? ApprovedUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ApprovedDate { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? OldRate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OldEffectiveDate { get; set; }
        [StringLength(2)]
        public string FreightIndicator { get; set; }
        [StringLength(50)]
        public string IncoTerms2 { get; set; }

        [ForeignKey(nameof(ApprovedUserId))]
        [InverseProperty(nameof(User.PriceChangeRequestItems))]
        public virtual User ApprovedUser { get; set; }
        [ForeignKey(nameof(PriceChangeRequestId))]
        [InverseProperty("PriceChangeRequestItems")]
        public virtual PriceChangeRequest PriceChangeRequest { get; set; }
        [ForeignKey(nameof(SapconditionId))]
        [InverseProperty("PriceChangeRequestItems")]
        public virtual Sapcondition Sapcondition { get; set; }
        [ForeignKey(nameof(SapmaterialGroupId))]
        [InverseProperty(nameof(SapcharacteristicOption.PriceChangeRequestItemSapmaterialGroups))]
        public virtual SapcharacteristicOption SapmaterialGroup { get; set; }
        [ForeignKey(nameof(SapmaterialPricingGroupId))]
        [InverseProperty(nameof(SapcharacteristicOption.PriceChangeRequestItemSapmaterialPricingGroups))]
        public virtual SapcharacteristicOption SapmaterialPricingGroup { get; set; }
        [ForeignKey(nameof(SappricingGroupId))]
        [InverseProperty(nameof(SapcharacteristicOption.PriceChangeRequestItemSappricingGroups))]
        public virtual SapcharacteristicOption SappricingGroup { get; set; }
        [ForeignKey(nameof(SapshipToId))]
        [InverseProperty("PriceChangeRequestItems")]
        public virtual SapshipTo SapshipTo { get; set; }
    }
}