// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("PriceSheetNote")]
    [Microsoft.EntityFrameworkCore.Index(nameof(SapsoldToId), nameof(RegionSapconditionGroupId), Name = "IX_PriceSheetNote", IsUnique = true)]
    public partial class PriceSheetNote
    {
        [Key]
        [Column("PriceSheetNoteID")]
        public long PriceSheetNoteId { get; set; }
        [Column("RegionSAPConditionGroupID")]
        public long? RegionSapconditionGroupId { get; set; }
        [StringLength(2000)]
        public string Notes { get; set; }
        [Column("SAPSoldToID")]
        public long? SapsoldToId { get; set; }

        [ForeignKey(nameof(RegionSapconditionGroupId))]
        [InverseProperty(nameof(SapconditionGroup.PriceSheetNotes))]
        public virtual SapconditionGroup RegionSapconditionGroup { get; set; }
        [ForeignKey(nameof(SapsoldToId))]
        [InverseProperty("PriceSheetNotes")]
        public virtual SapsoldTo SapsoldTo { get; set; }
    }
}