// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("PriceChangeRequest")]
    public partial class PriceChangeRequest
    {
        public PriceChangeRequest()
        {
            PriceChangeRequestItems = new HashSet<PriceChangeRequestItem>();
        }

        [Key]
        [Column("PriceChangeRequestID")]
        public long PriceChangeRequestId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [Column("UserID")]
        public long UserId { get; set; }
        [Column("SAPSoldToID")]
        public long? SapsoldToId { get; set; }
        [Column("RegionSAPConditionGroupID")]
        public long? RegionSapconditionGroupId { get; set; }
        [Column("TierSAPConditionGroupID")]
        public long? TierSapconditionGroupId { get; set; }
        [StringLength(3)]
        public string Currency { get; set; }

        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("PriceChangeRequests")]
        public virtual Division Division { get; set; }
        [ForeignKey(nameof(RegionSapconditionGroupId))]
        [InverseProperty(nameof(SapconditionGroup.PriceChangeRequestRegionSapconditionGroups))]
        public virtual SapconditionGroup RegionSapconditionGroup { get; set; }
        [ForeignKey(nameof(SapsoldToId))]
        [InverseProperty("PriceChangeRequests")]
        public virtual SapsoldTo SapsoldTo { get; set; }
        [ForeignKey(nameof(TierSapconditionGroupId))]
        [InverseProperty(nameof(SapconditionGroup.PriceChangeRequestTierSapconditionGroups))]
        public virtual SapconditionGroup TierSapconditionGroup { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("PriceChangeRequests")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(PriceChangeRequestItem.PriceChangeRequest))]
        public virtual ICollection<PriceChangeRequestItem> PriceChangeRequestItems { get; set; }
    }
}