// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ProductLine")]
    public partial class ProductLine
    {
        public ProductLine()
        {
            SapcharacteristicOptions = new HashSet<SapcharacteristicOption>();
            Sapshipments = new HashSet<Sapshipment>();
        }

        [Key]
        [Column("ProductLineID")]
        public long ProductLineId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [StringLength(50)]
        public string Name { get; set; }

        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("ProductLines")]
        public virtual Division Division { get; set; }
        [InverseProperty(nameof(SapcharacteristicOption.ProductLine))]
        public virtual ICollection<SapcharacteristicOption> SapcharacteristicOptions { get; set; }
        [InverseProperty(nameof(Sapshipment.ProductLine))]
        public virtual ICollection<Sapshipment> Sapshipments { get; set; }
    }
}