// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("QuickSearchTemplate")]
    public partial class QuickSearchTemplate
    {
        public QuickSearchTemplate()
        {
            QuickSearchCriteria = new HashSet<QuickSearchCriterion>();
        }

        [Key]
        public long TemplateId { get; set; }
        public long PersonId { get; set; }
        [Required]
        [StringLength(100)]
        public string TemplateName { get; set; }
        public long SoldToId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }

        [InverseProperty(nameof(QuickSearchCriterion.Template))]
        public virtual ICollection<QuickSearchCriterion> QuickSearchCriteria { get; set; }
    }
}