// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("QuoteSAPCondition")]
    [Microsoft.EntityFrameworkCore.Index(nameof(QuoteId), nameof(SapconditionId), Name = "IX_QuoteSAPPricingCondition", IsUnique = true)]
    public partial class QuoteSapcondition
    {
        [Key]
        [Column("QuoteSAPConditionID")]
        public long QuoteSapconditionId { get; set; }
        [Column("QuoteID")]
        public long QuoteId { get; set; }
        [Column("SAPConditionID")]
        public long SapconditionId { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? Rate { get; set; }
        [Required]
        [StringLength(5)]
        public string RateUnit { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ValidTo { get; set; }
        public int PricePer { get; set; }
        [Required]
        [StringLength(3)]
        public string PricePerUnit { get; set; }

        [ForeignKey(nameof(QuoteId))]
        [InverseProperty("QuoteSapconditions")]
        public virtual Quote Quote { get; set; }
        [ForeignKey(nameof(SapconditionId))]
        [InverseProperty("QuoteSapconditions")]
        public virtual Sapcondition Sapcondition { get; set; }
    }
}