// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("QuoteMaterial")]
    public partial class QuoteMaterial
    {
        public QuoteMaterial()
        {
            QuoteMaterialSapconditions = new HashSet<QuoteMaterialSapcondition>();
            Rollings = new HashSet<Rolling>();
            Stocks = new HashSet<Stock>();
        }

        [Key]
        [Column("QuoteMaterialID")]
        public long QuoteMaterialId { get; set; }
        [Column("QuoteID")]
        public long QuoteId { get; set; }
        [Column("SAPMaterialID")]
        public long SapmaterialId { get; set; }
        public int? Quantity { get; set; }
        [Column("SAPMaterialUnitOfMeasureID")]
        public long? SapmaterialUnitOfMeasureId { get; set; }
        [StringLength(2000)]
        public string Comments { get; set; }
        public int? Bundling1 { get; set; }
        public int? Bundling2 { get; set; }
        [StringLength(25)]
        public string PrintedComments { get; set; }
        [Column("StockSAPCode")]
        [StringLength(50)]
        public string StockSapcode { get; set; }
        [Column("SAPSalesOrderItemID")]
        public long? SapsalesOrderItemId { get; set; }
        [Column("SAPTubeStandardID")]
        public long? SaptubeStandardId { get; set; }
        [Column(TypeName = "decimal(18, 4)")]
        public decimal? Length { get; set; }
        public int? LengthFeet { get; set; }
        public int? LengthInches { get; set; }
        [StringLength(10)]
        public string LengthFractionalInches { get; set; }
        [Column("SAPKleenkoteColorID")]
        public long? SapkleenkoteColorId { get; set; }
        [Column("SAPEpoxycoatColorID")]
        public long? SapepoxycoatColorId { get; set; }
        [Column("SAPSpecificationID")]
        public long? SapspecificationId { get; set; }
        [Column("SAPSalesInstructionID")]
        public long? SapsalesInstructionId { get; set; }
        [Column(TypeName = "decimal(17, 3)")]
        public decimal? WeightPerFoot { get; set; }
        [StringLength(25)]
        public string StockMaterialNumber { get; set; }
        public bool? PlaceOnSalesOrder { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PromiseDate { get; set; }

        [ForeignKey(nameof(QuoteId))]
        [InverseProperty("QuoteMaterials")]
        public virtual Quote Quote { get; set; }
        [ForeignKey(nameof(SapepoxycoatColorId))]
        [InverseProperty(nameof(SapcharacteristicOption.QuoteMaterialSapepoxycoatColors))]
        public virtual SapcharacteristicOption SapepoxycoatColor { get; set; }
        [ForeignKey(nameof(SapkleenkoteColorId))]
        [InverseProperty(nameof(SapcharacteristicOption.QuoteMaterialSapkleenkoteColors))]
        public virtual SapcharacteristicOption SapkleenkoteColor { get; set; }
        [ForeignKey(nameof(SapmaterialId))]
        [InverseProperty("QuoteMaterials")]
        public virtual Sapmaterial Sapmaterial { get; set; }
        [ForeignKey(nameof(SapmaterialUnitOfMeasureId))]
        [InverseProperty(nameof(SapcharacteristicOption.QuoteMaterialSapmaterialUnitOfMeasures))]
        public virtual SapcharacteristicOption SapmaterialUnitOfMeasure { get; set; }
        [ForeignKey(nameof(SapsalesInstructionId))]
        [InverseProperty(nameof(SapcharacteristicOption.QuoteMaterialSapsalesInstructions))]
        public virtual SapcharacteristicOption SapsalesInstruction { get; set; }
        [ForeignKey(nameof(SapsalesOrderItemId))]
        [InverseProperty("QuoteMaterials")]
        public virtual SapsalesOrderItem SapsalesOrderItem { get; set; }
        [ForeignKey(nameof(SapspecificationId))]
        [InverseProperty(nameof(SapcharacteristicOption.QuoteMaterialSapspecifications))]
        public virtual SapcharacteristicOption Sapspecification { get; set; }
        [ForeignKey(nameof(SaptubeStandardId))]
        [InverseProperty(nameof(SapcharacteristicOption.QuoteMaterialSaptubeStandards))]
        public virtual SapcharacteristicOption SaptubeStandard { get; set; }
        [InverseProperty(nameof(QuoteMaterialSapcondition.QuoteMaterial))]
        public virtual ICollection<QuoteMaterialSapcondition> QuoteMaterialSapconditions { get; set; }
        [InverseProperty(nameof(Rolling.QuoteMaterial))]
        public virtual ICollection<Rolling> Rollings { get; set; }
        [InverseProperty(nameof(Stock.QuoteMaterial))]
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}