// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("QuoteMaterialSAPCondition")]
    [Microsoft.EntityFrameworkCore.Index(nameof(QuoteMaterialId), nameof(SapconditionId), Name = "IX_QuoteMaterialSAPPricingCondition", IsUnique = true)]
    public partial class QuoteMaterialSapcondition
    {
        [Key]
        [Column("QuoteMaterialSAPConditionID")]
        public long QuoteMaterialSapconditionId { get; set; }
        [Column("QuoteMaterialID")]
        public long QuoteMaterialId { get; set; }
        [Column("SAPConditionID")]
        public long SapconditionId { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? Rate { get; set; }
        [Required]
        [StringLength(5)]
        public string RateUnit { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ValidTo { get; set; }
        public int PricePer { get; set; }
        [Required]
        [StringLength(3)]
        public string PricePerUnit { get; set; }

        [ForeignKey(nameof(QuoteMaterialId))]
        [InverseProperty("QuoteMaterialSapconditions")]
        public virtual QuoteMaterial QuoteMaterial { get; set; }
        [ForeignKey(nameof(SapconditionId))]
        [InverseProperty("QuoteMaterialSapconditions")]
        public virtual Sapcondition Sapcondition { get; set; }
    }
}