// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("QuoteStatusChange")]
    public partial class QuoteStatusChange
    {
        [Key]
        [Column("QuoteStatusChangeID")]
        public long QuoteStatusChangeId { get; set; }
        [Column("QuoteID")]
        public long QuoteId { get; set; }
        [Column("QuoteStatusID")]
        public long QuoteStatusId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }

        [ForeignKey(nameof(QuoteId))]
        [InverseProperty("QuoteStatusChanges")]
        public virtual Quote Quote { get; set; }
        [ForeignKey(nameof(QuoteStatusId))]
        [InverseProperty("QuoteStatusChanges")]
        public virtual QuoteStatus QuoteStatus { get; set; }
    }
}