// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("Round")]
    public partial class Round
    {
        [Key]
        [Column("RoundID")]
        public int RoundId { get; set; }
        [Column(TypeName = "decimal(9, 4)")]
        public decimal Size { get; set; }
        [Required]
        [StringLength(50)]
        public string MaterialGroup { get; set; }
        [Column("NPS")]
        public bool? Nps { get; set; }
        [Column("NPSSize", TypeName = "decimal(9, 4)")]
        public decimal? Npssize { get; set; }
    }
}