// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPBundlingOption")]
    [Microsoft.EntityFrameworkCore.Index(nameof(LengthLow), nameof(LengthHigh), nameof(Bundling1), nameof(Bundling2), Name = "IX_SAPBundlingOption")]
    public partial class SapbundlingOption
    {
        [Key]
        [Column("SAPBundlingOptionID")]
        public long SapbundlingOptionId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Column(TypeName = "decimal(18, 4)")]
        public decimal LengthLow { get; set; }
        [Column(TypeName = "decimal(18, 4)")]
        public decimal LengthHigh { get; set; }
        public int Bundling1 { get; set; }
        public int Bundling2 { get; set; }
        [StringLength(10)]
        public string Plant { get; set; }

        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("SapbundlingOptions")]
        public virtual Division Division { get; set; }
    }
}