// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPCharacteristicType")]
    [Microsoft.EntityFrameworkCore.Index(nameof(DivisionId), nameof(Name), Name = "IX_SAPCharacteristicType", IsUnique = true)]
    public partial class SapcharacteristicType
    {
        public SapcharacteristicType()
        {
            SapcharacteristicOptions = new HashSet<SapcharacteristicOption>();
        }

        [Key]
        [Column("SAPCharacteristicTypeID")]
        public long SapcharacteristicTypeId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [Column("SAPCode")]
        [StringLength(50)]
        public string Sapcode { get; set; }
        public bool Active { get; set; }
        public int? SortOrder { get; set; }

        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("SapcharacteristicTypes")]
        public virtual Division Division { get; set; }
        [InverseProperty(nameof(SapcharacteristicOption.SapcharacteristicType))]
        public virtual ICollection<SapcharacteristicOption> SapcharacteristicOptions { get; set; }
    }
}