// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Keyless]
    [Table("SAPCustomerGroupSAPSalesOrganization")]
    [Microsoft.EntityFrameworkCore.Index(nameof(SapcustomerGroupId), nameof(SapsalesOrganizationId), Name = "IX_SAPCustomerGroupSAPSalesOrganization", IsUnique = true)]
    public partial class SapcustomerGroupSapsalesOrganization
    {
        [Column("SAPCustomerGroupID")]
        public long SapcustomerGroupId { get; set; }
        [Column("SAPSalesOrganizationID")]
        public long SapsalesOrganizationId { get; set; }

        [ForeignKey(nameof(SapcustomerGroupId))]
        public virtual SapcustomerGroup SapcustomerGroup { get; set; }
        [ForeignKey(nameof(SapsalesOrganizationId))]
        public virtual SapsalesOrganization SapsalesOrganization { get; set; }
    }
}