// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPCharacteristicOption")]
    public partial class SapcharacteristicOption
    {
        public SapcharacteristicOption()
        {
            DealsMaterialPricingGroups = new HashSet<DealsMaterialPricingGroup>();
            DealsPricingGroups = new HashSet<DealsPricingGroup>();
            PriceChangeRequestItemSapmaterialGroups = new HashSet<PriceChangeRequestItem>();
            PriceChangeRequestItemSapmaterialPricingGroups = new HashSet<PriceChangeRequestItem>();
            PriceChangeRequestItemSappricingGroups = new HashSet<PriceChangeRequestItem>();
            QuoteMaterialSapepoxycoatColors = new HashSet<QuoteMaterial>();
            QuoteMaterialSapkleenkoteColors = new HashSet<QuoteMaterial>();
            QuoteMaterialSapmaterialUnitOfMeasures = new HashSet<QuoteMaterial>();
            QuoteMaterialSapsalesInstructions = new HashSet<QuoteMaterial>();
            QuoteMaterialSapspecifications = new HashSet<QuoteMaterial>();
            QuoteMaterialSaptubeStandards = new HashSet<QuoteMaterial>();
            SapcustomerTexts = new HashSet<SapcustomerText>();
            SapmaterialSapalternateCoilIndicators = new HashSet<Sapmaterial>();
            SapmaterialSapepoxycoatColors = new HashSet<Sapmaterial>();
            SapmaterialSapkleenkoteColors = new HashSet<Sapmaterial>();
            SapmaterialSapmaterialGroups = new HashSet<Sapmaterial>();
            SapmaterialSapmaterialPricingGroups = new HashSet<Sapmaterial>();
            SapmaterialSapmaterialTypes = new HashSet<Sapmaterial>();
            SapmaterialSapmetalGrades = new HashSet<Sapmaterial>();
            SapmaterialSappricingGroups = new HashSet<Sapmaterial>();
            SapmaterialSapproductColorFinishes = new HashSet<Sapmaterial>();
            SapmaterialSapproductEndFinishEnergexes = new HashSet<Sapmaterial>();
            SapmaterialSapproductEndFinishes = new HashSet<Sapmaterial>();
            SapmaterialSapproductGroups = new HashSet<Sapmaterial>();
            SapmaterialSapproductLines = new HashSet<Sapmaterial>();
            SapmaterialSapproductTypes = new HashSet<Sapmaterial>();
            SapmaterialSapsalesInstructions = new HashSet<Sapmaterial>();
            SapmaterialSapspecifications = new HashSet<Sapmaterial>();
            SapmaterialSaptubeShapes = new HashSet<Sapmaterial>();
            SapmaterialSaptubeStandards = new HashSet<Sapmaterial>();
            SapshipToSapsalesOrganizations = new HashSet<SapshipToSapsalesOrganization>();
            SapstockSapspecifications = new HashSet<Sapstock>();
            SapstockSaptubeStandards = new HashSet<Sapstock>();
            ShoppingCartSaprollings = new HashSet<ShoppingCartSaprolling>();
            Zep1s = new HashSet<Zep1>();
            Zg01s = new HashSet<Zg01>();
            Zr00s = new HashSet<Zr00>();
            Zr01s = new HashSet<Zr01>();
            Zr04s = new HashSet<Zr04>();
        }

        [Key]
        [Column("SAPCharacteristicOptionID")]
        public long SapcharacteristicOptionId { get; set; }
        [Column("SAPCharacteristicTypeID")]
        public long SapcharacteristicTypeId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [Column("SAPCode")]
        [StringLength(50)]
        public string Sapcode { get; set; }
        public bool Active { get; set; }
        public int? SortOrder { get; set; }
        [Column("ProductLineID")]
        public long? ProductLineId { get; set; }

        [ForeignKey(nameof(ProductLineId))]
        [InverseProperty("SapcharacteristicOptions")]
        public virtual ProductLine ProductLine { get; set; }
        [ForeignKey(nameof(SapcharacteristicTypeId))]
        [InverseProperty("SapcharacteristicOptions")]
        public virtual SapcharacteristicType SapcharacteristicType { get; set; }
        [InverseProperty(nameof(DealsMaterialPricingGroup.Zr00Navigation))]
        public virtual ICollection<DealsMaterialPricingGroup> DealsMaterialPricingGroups { get; set; }
        [InverseProperty(nameof(DealsPricingGroup.Zr01Navigation))]
        public virtual ICollection<DealsPricingGroup> DealsPricingGroups { get; set; }
        [InverseProperty(nameof(PriceChangeRequestItem.SapmaterialGroup))]
        public virtual ICollection<PriceChangeRequestItem> PriceChangeRequestItemSapmaterialGroups { get; set; }
        [InverseProperty(nameof(PriceChangeRequestItem.SapmaterialPricingGroup))]
        public virtual ICollection<PriceChangeRequestItem> PriceChangeRequestItemSapmaterialPricingGroups { get; set; }
        [InverseProperty(nameof(PriceChangeRequestItem.SappricingGroup))]
        public virtual ICollection<PriceChangeRequestItem> PriceChangeRequestItemSappricingGroups { get; set; }
        [InverseProperty(nameof(QuoteMaterial.SapepoxycoatColor))]
        public virtual ICollection<QuoteMaterial> QuoteMaterialSapepoxycoatColors { get; set; }
        [InverseProperty(nameof(QuoteMaterial.SapkleenkoteColor))]
        public virtual ICollection<QuoteMaterial> QuoteMaterialSapkleenkoteColors { get; set; }
        [InverseProperty(nameof(QuoteMaterial.SapmaterialUnitOfMeasure))]
        public virtual ICollection<QuoteMaterial> QuoteMaterialSapmaterialUnitOfMeasures { get; set; }
        [InverseProperty(nameof(QuoteMaterial.SapsalesInstruction))]
        public virtual ICollection<QuoteMaterial> QuoteMaterialSapsalesInstructions { get; set; }
        [InverseProperty(nameof(QuoteMaterial.Sapspecification))]
        public virtual ICollection<QuoteMaterial> QuoteMaterialSapspecifications { get; set; }
        [InverseProperty(nameof(QuoteMaterial.SaptubeStandard))]
        public virtual ICollection<QuoteMaterial> QuoteMaterialSaptubeStandards { get; set; }
        [InverseProperty(nameof(SapcustomerText.SapcustomerTextType))]
        public virtual ICollection<SapcustomerText> SapcustomerTexts { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapalternateCoilIndicator))]
        public virtual ICollection<Sapmaterial> SapmaterialSapalternateCoilIndicators { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapepoxycoatColor))]
        public virtual ICollection<Sapmaterial> SapmaterialSapepoxycoatColors { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapkleenkoteColor))]
        public virtual ICollection<Sapmaterial> SapmaterialSapkleenkoteColors { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapmaterialGroup))]
        public virtual ICollection<Sapmaterial> SapmaterialSapmaterialGroups { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapmaterialPricingGroup))]
        public virtual ICollection<Sapmaterial> SapmaterialSapmaterialPricingGroups { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapmaterialType))]
        public virtual ICollection<Sapmaterial> SapmaterialSapmaterialTypes { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapmetalGrade))]
        public virtual ICollection<Sapmaterial> SapmaterialSapmetalGrades { get; set; }
        [InverseProperty(nameof(Sapmaterial.SappricingGroup))]
        public virtual ICollection<Sapmaterial> SapmaterialSappricingGroups { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapproductColorFinish))]
        public virtual ICollection<Sapmaterial> SapmaterialSapproductColorFinishes { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapproductEndFinishEnergex))]
        public virtual ICollection<Sapmaterial> SapmaterialSapproductEndFinishEnergexes { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapproductEndFinish))]
        public virtual ICollection<Sapmaterial> SapmaterialSapproductEndFinishes { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapproductGroup))]
        public virtual ICollection<Sapmaterial> SapmaterialSapproductGroups { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapproductLine))]
        public virtual ICollection<Sapmaterial> SapmaterialSapproductLines { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapproductType))]
        public virtual ICollection<Sapmaterial> SapmaterialSapproductTypes { get; set; }
        [InverseProperty(nameof(Sapmaterial.SapsalesInstruction))]
        public virtual ICollection<Sapmaterial> SapmaterialSapsalesInstructions { get; set; }
        [InverseProperty(nameof(Sapmaterial.Sapspecification))]
        public virtual ICollection<Sapmaterial> SapmaterialSapspecifications { get; set; }
        [InverseProperty(nameof(Sapmaterial.SaptubeShape))]
        public virtual ICollection<Sapmaterial> SapmaterialSaptubeShapes { get; set; }
        [InverseProperty(nameof(Sapmaterial.SaptubeStandard))]
        public virtual ICollection<Sapmaterial> SapmaterialSaptubeStandards { get; set; }
        [InverseProperty(nameof(SapshipToSapsalesOrganization.SappaymentTerms))]
        public virtual ICollection<SapshipToSapsalesOrganization> SapshipToSapsalesOrganizations { get; set; }
        [InverseProperty(nameof(Sapstock.Sapspecification))]
        public virtual ICollection<Sapstock> SapstockSapspecifications { get; set; }
        [InverseProperty(nameof(Sapstock.SaptubeStandard))]
        public virtual ICollection<Sapstock> SapstockSaptubeStandards { get; set; }
        [InverseProperty(nameof(ShoppingCartSaprolling.SaptubeStandard))]
        public virtual ICollection<ShoppingCartSaprolling> ShoppingCartSaprollings { get; set; }
        [InverseProperty(nameof(Zep1.SappricingGroup))]
        public virtual ICollection<Zep1> Zep1s { get; set; }
        [InverseProperty(nameof(Zg01.SaptubeStandard))]
        public virtual ICollection<Zg01> Zg01s { get; set; }
        [InverseProperty(nameof(Zr00.SapmaterialPricingGroup))]
        public virtual ICollection<Zr00> Zr00s { get; set; }
        [InverseProperty(nameof(Zr01.SappricingGroup))]
        public virtual ICollection<Zr01> Zr01s { get; set; }
        [InverseProperty(nameof(Zr04.SapmaterialGroup))]
        public virtual ICollection<Zr04> Zr04s { get; set; }
    }
}