// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPCustomerGroup")]
    [Microsoft.EntityFrameworkCore.Index(nameof(Sapcode), Name = "IX_SAPCustomerGroup", IsUnique = true)]
    public partial class SapcustomerGroup
    {
        public SapcustomerGroup()
        {
            SapcustomerGroupUsers = new HashSet<SapcustomerGroupUser>();
            SapshipToSapsalesOrganizations = new HashSet<SapshipToSapsalesOrganization>();
            SapshipTos = new HashSet<SapshipTo>();
        }

        [Key]
        [Column("SAPCustomerGroupID")]
        public long SapcustomerGroupId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [Column("SAPCode")]
        [StringLength(50)]
        public string Sapcode { get; set; }
        [Column("UserID")]
        public long? UserId { get; set; }
        [Column("RegionalManagerUserID")]
        public long? RegionalManagerUserId { get; set; }

        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("SapcustomerGroups")]
        public virtual Division Division { get; set; }
        [ForeignKey(nameof(RegionalManagerUserId))]
        [InverseProperty("SapcustomerGroupRegionalManagerUsers")]
        public virtual User RegionalManagerUser { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("SapcustomerGroupUsers")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(SapcustomerGroupUser.SapcustomerGroup))]
        public virtual ICollection<SapcustomerGroupUser> SapcustomerGroupUsers { get; set; }
        [InverseProperty(nameof(SapshipToSapsalesOrganization.SapcustomerGroup))]
        public virtual ICollection<SapshipToSapsalesOrganization> SapshipToSapsalesOrganizations { get; set; }
        [InverseProperty(nameof(SapshipTo.SapcustomerGroup))]
        public virtual ICollection<SapshipTo> SapshipTos { get; set; }
    }
}