// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPCustomerServiceRep")]
    public partial class SapcustomerServiceRep
    {
        public SapcustomerServiceRep()
        {
            SapshipToSapsalesOrganizations = new HashSet<SapshipToSapsalesOrganization>();
        }

        [Key]
        [Column("SAPCustomerServiceRepID")]
        public long SapcustomerServiceRepId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [Column("SAPCode")]
        [StringLength(50)]
        public string Sapcode { get; set; }
        [Column("UserID")]
        public long? UserId { get; set; }

        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("SapcustomerServiceReps")]
        public virtual Division Division { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("SapcustomerServiceReps")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(SapshipToSapsalesOrganization.SapcustomerServiceRep))]
        public virtual ICollection<SapshipToSapsalesOrganization> SapshipToSapsalesOrganizations { get; set; }
    }
}