// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPDeliveryType")]
    public partial class SapdeliveryType
    {
        public SapdeliveryType()
        {
            Sapshipments = new HashSet<Sapshipment>();
        }

        [Key]
        [Column("SAPDeliveryTypeID")]
        public long SapdeliveryTypeId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [Column("SAPCode")]
        [StringLength(50)]
        public string Sapcode { get; set; }

        [InverseProperty(nameof(Sapshipment.SapdeliveryType))]
        public virtual ICollection<Sapshipment> Sapshipments { get; set; }
    }
}