// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Keyless]
    [Table("SAPMaterialSAPBundlingOption")]
    [Microsoft.EntityFrameworkCore.Index(nameof(SapmaterialId), nameof(SapbundlingOptionId), Name = "IX_SAPMaterialSAPBundlingOption", IsUnique = true)]
    public partial class SapmaterialSapbundlingOption
    {
        [Column("SAPMaterialID")]
        public long SapmaterialId { get; set; }
        [Column("SAPBundlingOptionID")]
        public long SapbundlingOptionId { get; set; }

        [ForeignKey(nameof(SapbundlingOptionId))]
        public virtual SapbundlingOption SapbundlingOption { get; set; }
        [ForeignKey(nameof(SapmaterialId))]
        public virtual Sapmaterial Sapmaterial { get; set; }
    }
}