// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPMaterialPlant")]
    public partial class SapmaterialPlant
    {
        [Key]
        [Column("SAPMaterialPlantID")]
        public long SapmaterialPlantId { get; set; }
        [Column("SAPMaterialID")]
        public long SapmaterialId { get; set; }
        [Column("PlantID")]
        public long PlantId { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? StandardPrice { get; set; }
        [Column(TypeName = "decimal(7, 2)")]
        public decimal? PriceUnit { get; set; }
        [StringLength(1)]
        public string PriceControlIndicator { get; set; }

        [ForeignKey(nameof(PlantId))]
        [InverseProperty("SapmaterialPlants")]
        public virtual Plant Plant { get; set; }
        [ForeignKey(nameof(SapmaterialId))]
        [InverseProperty("SapmaterialPlants")]
        public virtual Sapmaterial Sapmaterial { get; set; }
    }
}