// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPMaterial")]
    public partial class Sapmaterial
    {
        public Sapmaterial()
        {
            Cmirs = new HashSet<Cmir>();
            QuoteMaterials = new HashSet<QuoteMaterial>();
            SapmaterialPlants = new HashSet<SapmaterialPlant>();
            SapmaterialUnitOfMeasures = new HashSet<SapmaterialUnitOfMeasure>();
            SapsalesOrderItems = new HashSet<SapsalesOrderItem>();
            Sapstocks = new HashSet<Sapstock>();
            ShoppingCartSaprollings = new HashSet<ShoppingCartSaprolling>();
        }

        [Key]
        [Column("SAPMaterialID")]
        public long SapmaterialId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(25)]
        public string Number { get; set; }
        [Column("SAPMaterialGroupID")]
        public long SapmaterialGroupId { get; set; }
        [Column("SAPMaterialTypeID")]
        public long? SapmaterialTypeId { get; set; }
        [Column("SAPAlternateCoilIndicatorID")]
        public long? SapalternateCoilIndicatorId { get; set; }
        public bool Cutting { get; set; }
        [Column("SAPKleenkoteColorID")]
        public long? SapkleenkoteColorId { get; set; }
        [Column("SAPEpoxycoatColorID")]
        public long? SapepoxycoatColorId { get; set; }
        [Column("SAPTubeShapeID")]
        public long? SaptubeShapeId { get; set; }
        [Column(TypeName = "decimal(18, 4)")]
        public decimal? Size { get; set; }
        [Column(TypeName = "decimal(18, 4)")]
        public decimal? Size2 { get; set; }
        [Column(TypeName = "decimal(17, 3)")]
        public decimal? Diameter { get; set; }
        [Column(TypeName = "decimal(18, 4)")]
        public decimal? Length { get; set; }
        public int? LengthFeet { get; set; }
        public int? LengthInches { get; set; }
        [Required]
        [StringLength(10)]
        public string LengthFractionalInches { get; set; }
        [Column(TypeName = "decimal(17, 3)")]
        public decimal? PieceWeight { get; set; }
        [Column(TypeName = "decimal(17, 3)")]
        public decimal? WeightPerFoot { get; set; }
        [Column("SAPTubeStandardID")]
        public long? SaptubeStandardId { get; set; }
        [Column(TypeName = "decimal(17, 3)")]
        public decimal? GaugeRestrictable { get; set; }
        public int? Bundling1 { get; set; }
        public int? Bundling2 { get; set; }
        public int? BundlingRound { get; set; }
        [Column("SAPSpecificationID")]
        public long? SapspecificationId { get; set; }
        [Column("SAPSalesInstructionID")]
        public long? SapsalesInstructionId { get; set; }
        public bool Configurable { get; set; }
        [Column("SAPMaterialPricingGroupID")]
        public long? SapmaterialPricingGroupId { get; set; }
        [Column("SAPPricingGroupID")]
        public long? SappricingGroupId { get; set; }
        [Column("SAPProductLineID")]
        public long? SapproductLineId { get; set; }
        [Column("SAPProductGroupID")]
        public long? SapproductGroupId { get; set; }
        [Column("SAPProductTypeID")]
        public long? SapproductTypeId { get; set; }
        [Column("SAPProductColorFinishID")]
        public long? SapproductColorFinishId { get; set; }
        [Column("SAPProductEndFinishID")]
        public long? SapproductEndFinishId { get; set; }
        [StringLength(4)]
        public string ProductSize { get; set; }
        [StringLength(4)]
        public string ProductGauge { get; set; }
        [Column(TypeName = "decimal(17, 3)")]
        public decimal? GrossWeight { get; set; }
        [Column(TypeName = "decimal(17, 3)")]
        public decimal? NetWeight { get; set; }
        [StringLength(2)]
        public string CommissionGroup { get; set; }
        [StringLength(2)]
        public string VolumeRebateGroup { get; set; }
        [Column("SAPProductEndFinishEnergexID")]
        public long? SapproductEndFinishEnergexId { get; set; }
        [Column("SAPMetalGradeID")]
        public long? SapmetalGradeId { get; set; }
        [Column("NPSDescription")]
        [StringLength(50)]
        public string Npsdescription { get; set; }
        public bool? BlockFromPortalRollings { get; set; }
        [StringLength(25)]
        public string PlanningMaterial { get; set; }
        [Column(TypeName = "decimal(17, 3)")]
        public decimal? BundleWeight { get; set; }
        [Column(TypeName = "decimal(18, 4)")]
        public decimal? TotalBundleLength { get; set; }
        public int? PieceperBundle { get; set; }
        [StringLength(25)]
        public string OldMaterialNumber { get; set; }

        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("Sapmaterials")]
        public virtual Division Division { get; set; }
        [ForeignKey(nameof(SapalternateCoilIndicatorId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapalternateCoilIndicators))]
        public virtual SapcharacteristicOption SapalternateCoilIndicator { get; set; }
        [ForeignKey(nameof(SapepoxycoatColorId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapepoxycoatColors))]
        public virtual SapcharacteristicOption SapepoxycoatColor { get; set; }
        [ForeignKey(nameof(SapkleenkoteColorId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapkleenkoteColors))]
        public virtual SapcharacteristicOption SapkleenkoteColor { get; set; }
        [ForeignKey(nameof(SapmaterialGroupId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapmaterialGroups))]
        public virtual SapcharacteristicOption SapmaterialGroup { get; set; }
        [ForeignKey(nameof(SapmaterialPricingGroupId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapmaterialPricingGroups))]
        public virtual SapcharacteristicOption SapmaterialPricingGroup { get; set; }
        [ForeignKey(nameof(SapmaterialTypeId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapmaterialTypes))]
        public virtual SapcharacteristicOption SapmaterialType { get; set; }
        [ForeignKey(nameof(SapmetalGradeId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapmetalGrades))]
        public virtual SapcharacteristicOption SapmetalGrade { get; set; }
        [ForeignKey(nameof(SappricingGroupId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSappricingGroups))]
        public virtual SapcharacteristicOption SappricingGroup { get; set; }
        [ForeignKey(nameof(SapproductColorFinishId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapproductColorFinishes))]
        public virtual SapcharacteristicOption SapproductColorFinish { get; set; }
        [ForeignKey(nameof(SapproductEndFinishId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapproductEndFinishes))]
        public virtual SapcharacteristicOption SapproductEndFinish { get; set; }
        [ForeignKey(nameof(SapproductEndFinishEnergexId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapproductEndFinishEnergexes))]
        public virtual SapcharacteristicOption SapproductEndFinishEnergex { get; set; }
        [ForeignKey(nameof(SapproductGroupId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapproductGroups))]
        public virtual SapcharacteristicOption SapproductGroup { get; set; }
        [ForeignKey(nameof(SapproductLineId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapproductLines))]
        public virtual SapcharacteristicOption SapproductLine { get; set; }
        [ForeignKey(nameof(SapproductTypeId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapproductTypes))]
        public virtual SapcharacteristicOption SapproductType { get; set; }
        [ForeignKey(nameof(SapsalesInstructionId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapsalesInstructions))]
        public virtual SapcharacteristicOption SapsalesInstruction { get; set; }
        [ForeignKey(nameof(SapspecificationId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSapspecifications))]
        public virtual SapcharacteristicOption Sapspecification { get; set; }
        [ForeignKey(nameof(SaptubeShapeId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSaptubeShapes))]
        public virtual SapcharacteristicOption SaptubeShape { get; set; }
        [ForeignKey(nameof(SaptubeStandardId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapmaterialSaptubeStandards))]
        public virtual SapcharacteristicOption SaptubeStandard { get; set; }
        [InverseProperty(nameof(Cmir.Sapmaterial))]
        public virtual ICollection<Cmir> Cmirs { get; set; }
        [InverseProperty(nameof(QuoteMaterial.Sapmaterial))]
        public virtual ICollection<QuoteMaterial> QuoteMaterials { get; set; }
        [InverseProperty(nameof(SapmaterialPlant.Sapmaterial))]
        public virtual ICollection<SapmaterialPlant> SapmaterialPlants { get; set; }
        [InverseProperty(nameof(SapmaterialUnitOfMeasure.Sapmaterial))]
        public virtual ICollection<SapmaterialUnitOfMeasure> SapmaterialUnitOfMeasures { get; set; }
        [InverseProperty(nameof(SapsalesOrderItem.Sapmaterial))]
        public virtual ICollection<SapsalesOrderItem> SapsalesOrderItems { get; set; }
        [InverseProperty(nameof(Sapstock.Sapmaterial))]
        public virtual ICollection<Sapstock> Sapstocks { get; set; }
        [InverseProperty(nameof(ShoppingCartSaprolling.Sapmaterial))]
        public virtual ICollection<ShoppingCartSaprolling> ShoppingCartSaprollings { get; set; }
    }
}