// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPMaterialUnitOfMeasure")]
    public partial class SapmaterialUnitOfMeasure
    {
        [Key]
        [Column("SAPMaterialUnitOfMeasureID")]
        public long SapmaterialUnitOfMeasureId { get; set; }
        [Column("SAPMaterialID")]
        public long SapmaterialId { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? Numerator { get; set; }
        [Column(TypeName = "decimal(18, 5)")]
        public decimal? Denominator { get; set; }
        [Column("BaseUnitOfMeasureID")]
        public long BaseUnitOfMeasureId { get; set; }
        [Column("AlternateUnitOfMeasureID")]
        public long AlternateUnitOfMeasureId { get; set; }

        [ForeignKey(nameof(AlternateUnitOfMeasureId))]
        [InverseProperty(nameof(SapunitOfMeasure.SapmaterialUnitOfMeasureAlternateUnitOfMeasures))]
        public virtual SapunitOfMeasure AlternateUnitOfMeasure { get; set; }
        [ForeignKey(nameof(BaseUnitOfMeasureId))]
        [InverseProperty(nameof(SapunitOfMeasure.SapmaterialUnitOfMeasureBaseUnitOfMeasures))]
        public virtual SapunitOfMeasure BaseUnitOfMeasure { get; set; }
        [ForeignKey(nameof(SapmaterialId))]
        [InverseProperty("SapmaterialUnitOfMeasures")]
        public virtual Sapmaterial Sapmaterial { get; set; }
    }
}