// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPStorageLocation")]
    public partial class SapstorageLocation
    {
        public SapstorageLocation()
        {
            SapsalesDeliveries = new HashSet<SapsalesDelivery>();
        }

        [Key]
        [Column("SAPStorageLocationID")]
        public long SapstorageLocationId { get; set; }
        [Required]
        [Column("SAPCode")]
        [StringLength(4)]
        public string Sapcode { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public bool Active { get; set; }
        [Column("PlantID")]
        public long PlantId { get; set; }

        [ForeignKey(nameof(PlantId))]
        [InverseProperty("SapstorageLocations")]
        public virtual Plant Plant { get; set; }
        [InverseProperty(nameof(SapsalesDelivery.SapstorageLocation))]
        public virtual ICollection<SapsalesDelivery> SapsalesDeliveries { get; set; }
    }
}