// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPSalesGroup")]
    [Microsoft.EntityFrameworkCore.Index(nameof(Sapcode), Name = "IX_SAPSalesGroup", IsUnique = true)]
    public partial class SapsalesGroup
    {
        public SapsalesGroup()
        {
            SapshipToSapsalesOrganizations = new HashSet<SapshipToSapsalesOrganization>();
            SapshipTos = new HashSet<SapshipTo>();
        }

        [Key]
        [Column("SAPSalesGroupID")]
        public long SapsalesGroupId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [Column("SAPCode")]
        [StringLength(50)]
        public string Sapcode { get; set; }
        [Column("UserID")]
        public long? UserId { get; set; }
        [Column("AlternateISR")]
        public long? AlternateIsr { get; set; }
        [Column("BoldChatID")]
        [StringLength(50)]
        public string BoldChatId { get; set; }

        [ForeignKey(nameof(AlternateIsr))]
        [InverseProperty("SapsalesGroupAlternateIsrNavigations")]
        public virtual User AlternateIsrNavigation { get; set; }
        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("SapsalesGroups")]
        public virtual Division Division { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("SapsalesGroupUsers")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(SapshipToSapsalesOrganization.SapsalesGroup))]
        public virtual ICollection<SapshipToSapsalesOrganization> SapshipToSapsalesOrganizations { get; set; }
        [InverseProperty(nameof(SapshipTo.SapsalesGroup))]
        public virtual ICollection<SapshipTo> SapshipTos { get; set; }
    }
}