// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPSalesOrganization")]
    public partial class SapsalesOrganization
    {
        public SapsalesOrganization()
        {
            Cmirs = new HashSet<Cmir>();
            SapcustomerTexts = new HashSet<SapcustomerText>();
            SapshipToSapsalesOrganizations = new HashSet<SapshipToSapsalesOrganization>();
        }

        [Key]
        [Column("SAPSalesOrganizationID")]
        public long SapsalesOrganizationId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [Column("SAPCode")]
        [StringLength(50)]
        public string Sapcode { get; set; }

        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("SapsalesOrganizations")]
        public virtual Division Division { get; set; }
        [InverseProperty(nameof(Cmir.SapsalesOrganization))]
        public virtual ICollection<Cmir> Cmirs { get; set; }
        [InverseProperty(nameof(SapcustomerText.SapsalesOrganization))]
        public virtual ICollection<SapcustomerText> SapcustomerTexts { get; set; }
        [InverseProperty(nameof(SapshipToSapsalesOrganization.SapsalesOrganization))]
        public virtual ICollection<SapshipToSapsalesOrganization> SapshipToSapsalesOrganizations { get; set; }
    }
}