// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPSoldToPlantExclusion")]
    public partial class SapsoldToPlantExclusion
    {
        [Key]
        [Column("SAPShipToID")]
        public long SapshipToId { get; set; }
        [Key]
        [Column("PlantID")]
        public long PlantId { get; set; }
        [Required]
        public bool? ViewStockRollings { get; set; }
        public bool? CanOrder { get; set; }

        [ForeignKey(nameof(PlantId))]
        [InverseProperty("SapsoldToPlantExclusions")]
        public virtual Plant Plant { get; set; }
        [ForeignKey(nameof(SapshipToId))]
        [InverseProperty(nameof(SapsoldTo.SapsoldToPlantExclusions))]
        public virtual SapsoldTo SapshipTo { get; set; }
    }
}