// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Keyless]
    [Table("SAPSalesGroupSAPSalesOrganization")]
    [Microsoft.EntityFrameworkCore.Index(nameof(SapsalesGroupId), nameof(SapsalesOrganizationId), Name = "IX_SAPSalesGroupSAPSalesOrganization", IsUnique = true)]
    public partial class SapsalesGroupSapsalesOrganization
    {
        [Column("SAPSalesGroupID")]
        public long SapsalesGroupId { get; set; }
        [Column("SAPSalesOrganizationID")]
        public long SapsalesOrganizationId { get; set; }

        [ForeignKey(nameof(SapsalesGroupId))]
        public virtual SapsalesGroup SapsalesGroup { get; set; }
        [ForeignKey(nameof(SapsalesOrganizationId))]
        public virtual SapsalesOrganization SapsalesOrganization { get; set; }
    }
}