// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPScrapOrder")]
    public partial class SapscrapOrder
    {
        [Key]
        [Column("SAPSalesOrderID")]
        public long SapsalesOrderId { get; set; }
        public int? Month { get; set; }
        public int? Year { get; set; }
        public bool Consignment { get; set; }

        [ForeignKey(nameof(SapsalesOrderId))]
        [InverseProperty("SapscrapOrder")]
        public virtual SapsalesOrder SapsalesOrder { get; set; }
    }
}