// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPShipTo")]
    [Microsoft.EntityFrameworkCore.Index(nameof(SapsalesGroupId), Name = "IDX_SAPShipto_SalesGrpId")]
    [Microsoft.EntityFrameworkCore.Index(nameof(DivisionId), nameof(Number), Name = "IX_SAPShipTo", IsUnique = true)]
    public partial class SapshipTo
    {
        public SapshipTo()
        {
            DealsBySoldToShipTos = new HashSet<DealsBySoldToShipTo>();
            FreightandFscs = new HashSet<FreightandFsc>();
            PriceChangeRequestItems = new HashSet<PriceChangeRequestItem>();
            Quotes = new HashSet<Quote>();
            SapcustomerTexts = new HashSet<SapcustomerText>();
            SapsalesDeliveries = new HashSet<SapsalesDelivery>();
            SapsalesOrderItems = new HashSet<SapsalesOrderItem>();
            SapsalesOrders = new HashSet<SapsalesOrder>();
            SapshipToSapsalesOrganizations = new HashSet<SapshipToSapsalesOrganization>();
            SapsoldToDefaultSapshipTos = new HashSet<SapsoldTo>();
            UserSapshipToExclusions = new HashSet<UserSapshipToExclusion>();
            Zr00s = new HashSet<Zr00>();
            Zr01s = new HashSet<Zr01>();
        }

        [Key]
        [Column("SAPShipToID")]
        public long SapshipToId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Required]
        [StringLength(10)]
        public string Number { get; set; }
        [Required]
        [StringLength(35)]
        public string Name { get; set; }
        [Required]
        [StringLength(35)]
        public string Address { get; set; }
        [Column("CityID")]
        public long CityId { get; set; }
        [Required]
        [StringLength(10)]
        public string PostalCode { get; set; }
        [Required]
        [StringLength(16)]
        public string Phone { get; set; }
        [Required]
        [StringLength(31)]
        public string Fax { get; set; }
        [Required]
        [StringLength(28)]
        public string IncoTerms2 { get; set; }
        [Required]
        [StringLength(5)]
        public string Currency { get; set; }
        [Column("FreightIndicatorSAPConditionGroupID")]
        public long? FreightIndicatorSapconditionGroupId { get; set; }
        [Column("FuelSurchargeSAPConditionGroupID")]
        public long? FuelSurchargeSapconditionGroupId { get; set; }
        public bool Active { get; set; }
        [Column("SAPCustomerGroupID")]
        public long? SapcustomerGroupId { get; set; }
        [Column("SAPSalesGroupID")]
        public long? SapsalesGroupId { get; set; }
        [StringLength(35)]
        public string Name2 { get; set; }
        public int? SortOrder { get; set; }
        public bool? AllowPrice { get; set; }
        public bool? Out { get; set; }

        [ForeignKey(nameof(CityId))]
        [InverseProperty("SapshipTos")]
        public virtual City City { get; set; }
        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("SapshipTos")]
        public virtual Division Division { get; set; }
        [ForeignKey(nameof(FreightIndicatorSapconditionGroupId))]
        [InverseProperty(nameof(SapconditionGroup.SapshipToFreightIndicatorSapconditionGroups))]
        public virtual SapconditionGroup FreightIndicatorSapconditionGroup { get; set; }
        [ForeignKey(nameof(FuelSurchargeSapconditionGroupId))]
        [InverseProperty(nameof(SapconditionGroup.SapshipToFuelSurchargeSapconditionGroups))]
        public virtual SapconditionGroup FuelSurchargeSapconditionGroup { get; set; }
        [ForeignKey(nameof(SapcustomerGroupId))]
        [InverseProperty("SapshipTos")]
        public virtual SapcustomerGroup SapcustomerGroup { get; set; }
        [ForeignKey(nameof(SapsalesGroupId))]
        [InverseProperty("SapshipTos")]
        public virtual SapsalesGroup SapsalesGroup { get; set; }
        [InverseProperty(nameof(SapsoldTo.SapshipTo))]
        public virtual SapsoldTo SapsoldToSapshipTo { get; set; }
        [InverseProperty(nameof(DealsBySoldToShipTo.SapshipTo))]
        public virtual ICollection<DealsBySoldToShipTo> DealsBySoldToShipTos { get; set; }
        [InverseProperty(nameof(FreightandFsc.Sapshipto))]
        public virtual ICollection<FreightandFsc> FreightandFscs { get; set; }
        [InverseProperty(nameof(PriceChangeRequestItem.SapshipTo))]
        public virtual ICollection<PriceChangeRequestItem> PriceChangeRequestItems { get; set; }
        [InverseProperty(nameof(Quote.SapshipTo))]
        public virtual ICollection<Quote> Quotes { get; set; }
        [InverseProperty(nameof(SapcustomerText.SapshipTo))]
        public virtual ICollection<SapcustomerText> SapcustomerTexts { get; set; }
        [InverseProperty(nameof(SapsalesDelivery.SapshipTo))]
        public virtual ICollection<SapsalesDelivery> SapsalesDeliveries { get; set; }
        [InverseProperty(nameof(SapsalesOrderItem.SapshipTo))]
        public virtual ICollection<SapsalesOrderItem> SapsalesOrderItems { get; set; }
        [InverseProperty(nameof(SapsalesOrder.SapshipTo))]
        public virtual ICollection<SapsalesOrder> SapsalesOrders { get; set; }
        [InverseProperty(nameof(SapshipToSapsalesOrganization.SapshipTo))]
        public virtual ICollection<SapshipToSapsalesOrganization> SapshipToSapsalesOrganizations { get; set; }
        [InverseProperty(nameof(SapsoldTo.DefaultSapshipTo))]
        public virtual ICollection<SapsoldTo> SapsoldToDefaultSapshipTos { get; set; }
        [InverseProperty(nameof(UserSapshipToExclusion.SapshipTo))]
        public virtual ICollection<UserSapshipToExclusion> UserSapshipToExclusions { get; set; }
        [InverseProperty(nameof(Zr00.Sapsoldto))]
        public virtual ICollection<Zr00> Zr00s { get; set; }
        [InverseProperty(nameof(Zr01.Sapsoldto))]
        public virtual ICollection<Zr01> Zr01s { get; set; }
    }
}