// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPShipToSAPSalesOrganization")]
    public partial class SapshipToSapsalesOrganization
    {
        [Key]
        [Column("SAPShipToSAPSalesOrganizationID")]
        public long SapshipToSapsalesOrganizationId { get; set; }
        [Column("SAPShipToID")]
        public long SapshipToId { get; set; }
        [Column("SAPSalesOrganizationID")]
        public long SapsalesOrganizationId { get; set; }
        [Column("SAPCustomerGroupID")]
        public long? SapcustomerGroupId { get; set; }
        [Column("SAPSalesGroupID")]
        public long? SapsalesGroupId { get; set; }
        [StringLength(3)]
        public string IncoTerms1 { get; set; }
        [StringLength(28)]
        public string IncoTerms2 { get; set; }
        [StringLength(5)]
        public string Currency { get; set; }
        [StringLength(1)]
        public string PricingProcedure { get; set; }
        [Column("SAPCustomerServiceRepID")]
        public long? SapcustomerServiceRepId { get; set; }
        [Column("SAPRegionID")]
        public long? SapregionId { get; set; }
        [Column("SAPTierID")]
        public long? SaptierId { get; set; }
        [Column("SAPPaymentTermsID")]
        public long? SappaymentTermsId { get; set; }
        public bool? Active { get; set; }
        [StringLength(10)]
        public string OrderBlock { get; set; }

        [ForeignKey(nameof(SapcustomerGroupId))]
        [InverseProperty("SapshipToSapsalesOrganizations")]
        public virtual SapcustomerGroup SapcustomerGroup { get; set; }
        [ForeignKey(nameof(SapcustomerServiceRepId))]
        [InverseProperty("SapshipToSapsalesOrganizations")]
        public virtual SapcustomerServiceRep SapcustomerServiceRep { get; set; }
        [ForeignKey(nameof(SappaymentTermsId))]
        [InverseProperty(nameof(SapcharacteristicOption.SapshipToSapsalesOrganizations))]
        public virtual SapcharacteristicOption SappaymentTerms { get; set; }
        [ForeignKey(nameof(SapregionId))]
        [InverseProperty("SapshipToSapsalesOrganizations")]
        public virtual Sapregion Sapregion { get; set; }
        [ForeignKey(nameof(SapsalesGroupId))]
        [InverseProperty("SapshipToSapsalesOrganizations")]
        public virtual SapsalesGroup SapsalesGroup { get; set; }
        [ForeignKey(nameof(SapsalesOrganizationId))]
        [InverseProperty("SapshipToSapsalesOrganizations")]
        public virtual SapsalesOrganization SapsalesOrganization { get; set; }
        [ForeignKey(nameof(SapshipToId))]
        [InverseProperty("SapshipToSapsalesOrganizations")]
        public virtual SapshipTo SapshipTo { get; set; }
        [ForeignKey(nameof(SaptierId))]
        [InverseProperty("SapshipToSapsalesOrganizations")]
        public virtual Saptier Saptier { get; set; }
    }
}