// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPScrapDelivery")]
    public partial class SapscrapDelivery
    {
        public SapscrapDelivery()
        {
            ScrapSales = new HashSet<ScrapSale>();
        }

        [Key]
        [Column("SAPDeliveryID")]
        public long SapdeliveryId { get; set; }

        [ForeignKey(nameof(SapdeliveryId))]
        [InverseProperty("SapscrapDelivery")]
        public virtual Sapdelivery Sapdelivery { get; set; }
        [InverseProperty(nameof(ScrapSale.SapscrapDelivery))]
        public virtual ICollection<ScrapSale> ScrapSales { get; set; }
    }
}