// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Keyless]
    [Table("SAPTierSAPSalesOrganization")]
    public partial class SaptierSapsalesOrganization
    {
        [Column("SAPTierID")]
        public long SaptierId { get; set; }
        [Column("SAPSalesOrganizationID")]
        public long SapsalesOrganizationId { get; set; }

        [ForeignKey(nameof(SapsalesOrganizationId))]
        public virtual SapsalesOrganization SapsalesOrganization { get; set; }
        [ForeignKey(nameof(SaptierId))]
        public virtual Saptier Saptier { get; set; }
    }
}