// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SAPUnitOfMeasure")]
    public partial class SapunitOfMeasure
    {
        public SapunitOfMeasure()
        {
            SapmaterialUnitOfMeasureAlternateUnitOfMeasures = new HashSet<SapmaterialUnitOfMeasure>();
            SapmaterialUnitOfMeasureBaseUnitOfMeasures = new HashSet<SapmaterialUnitOfMeasure>();
        }

        [Key]
        [Column("SAPUnitOfMeasureID")]
        public long SapunitOfMeasureId { get; set; }
        [Required]
        [Column("SAPCode")]
        [StringLength(3)]
        public string Sapcode { get; set; }

        [InverseProperty(nameof(SapmaterialUnitOfMeasure.AlternateUnitOfMeasure))]
        public virtual ICollection<SapmaterialUnitOfMeasure> SapmaterialUnitOfMeasureAlternateUnitOfMeasures { get; set; }
        [InverseProperty(nameof(SapmaterialUnitOfMeasure.BaseUnitOfMeasure))]
        public virtual ICollection<SapmaterialUnitOfMeasure> SapmaterialUnitOfMeasureBaseUnitOfMeasures { get; set; }
    }
}