// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Keyless]
    [Table("ScrapSaleBox")]
    public partial class ScrapSaleBox
    {
        [Column("ScrapSaleID")]
        public long ScrapSaleId { get; set; }
        [Column("BoxID")]
        public long BoxId { get; set; }

        [ForeignKey(nameof(BoxId))]
        public virtual Box Box { get; set; }
        [ForeignKey(nameof(ScrapSaleId))]
        public virtual ScrapSale ScrapSale { get; set; }
    }
}