// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Keyless]
    [Table("ScrapSaleSAPSalesOrderItem")]
    public partial class ScrapSaleSapsalesOrderItem
    {
        [Column("ScrapSaleID")]
        public long ScrapSaleId { get; set; }
        [Column("SAPSalesOrderItemID")]
        public long SapsalesOrderItemId { get; set; }

        [ForeignKey(nameof(SapsalesOrderItemId))]
        public virtual SapsalesOrderItem SapsalesOrderItem { get; set; }
        [ForeignKey(nameof(ScrapSaleId))]
        public virtual ScrapSale ScrapSale { get; set; }
    }
}