// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ScrapSale")]
    public partial class ScrapSale
    {
        [Key]
        [Column("ScrapSaleID")]
        public long ScrapSaleId { get; set; }
        [Column("DivisionID")]
        public long DivisionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [Column("ScrapSAPSoldToID")]
        public long? ScrapSapsoldToId { get; set; }
        [Column("RandomLengthSAPSoldToID")]
        public long? RandomLengthSapsoldToId { get; set; }
        [Column("TruckID")]
        public long? TruckId { get; set; }
        [Column("TrailerID")]
        public long? TrailerId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? GrossWeight { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? TareWeight { get; set; }
        [Column("PlantID")]
        public long PlantId { get; set; }
        [Column("SAPScrapDeliveryID")]
        public long? SapscrapDeliveryId { get; set; }
        [Column("WeightAddedToSAPSalesOrder")]
        public bool? WeightAddedToSapsalesOrder { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? WeightAddedToInventory { get; set; }
        public bool? Cancelled { get; set; }

        [ForeignKey(nameof(DivisionId))]
        [InverseProperty("ScrapSales")]
        public virtual Division Division { get; set; }
        [ForeignKey(nameof(PlantId))]
        [InverseProperty("ScrapSales")]
        public virtual Plant Plant { get; set; }
        [ForeignKey(nameof(RandomLengthSapsoldToId))]
        [InverseProperty("ScrapSales")]
        public virtual RandomLengthSapsoldTo RandomLengthSapsoldTo { get; set; }
        [ForeignKey(nameof(SapscrapDeliveryId))]
        [InverseProperty("ScrapSales")]
        public virtual SapscrapDelivery SapscrapDelivery { get; set; }
        [ForeignKey(nameof(ScrapSapsoldToId))]
        [InverseProperty("ScrapSales")]
        public virtual ScrapSapsoldTo ScrapSapsoldTo { get; set; }
        [ForeignKey(nameof(TrailerId))]
        [InverseProperty("ScrapSales")]
        public virtual Trailer Trailer { get; set; }
        [ForeignKey(nameof(TruckId))]
        [InverseProperty("ScrapSales")]
        public virtual Truck Truck { get; set; }
    }
}