// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ShippingCart")]
    public partial class ShippingCart
    {
        public ShippingCart()
        {
            ShippingCartSapsalesOrderItems = new HashSet<ShippingCartSapsalesOrderItem>();
        }

        [Key]
        [Column("ShippingCartID")]
        public long ShippingCartId { get; set; }
        [Column("UserID")]
        public long UserId { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [StringLength(50)]
        public string SoldTo { get; set; }
        [StringLength(50)]
        public string ShipTo { get; set; }
        public long? SubTotal { get; set; }
        [StringLength(50)]
        public string Plant { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("ShippingCarts")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(ShippingCartSapsalesOrderItem.ShippingCart))]
        public virtual ICollection<ShippingCartSapsalesOrderItem> ShippingCartSapsalesOrderItems { get; set; }
    }
}