// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ShipmentCostType")]
    public partial class ShipmentCostType
    {
        public ShipmentCostType()
        {
            PendingShipmentCosts = new HashSet<PendingShipmentCost>();
            ShipmentCosts = new HashSet<ShipmentCost>();
        }

        [Key]
        [Column("ShipmentCostTypeID")]
        public long ShipmentCostTypeId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(10)]
        public string Code { get; set; }
        [Column("IPS")]
        public bool Ips { get; set; }
        [Column("SAP")]
        public bool Sap { get; set; }

        [InverseProperty(nameof(PendingShipmentCost.ShipmentCostType))]
        public virtual ICollection<PendingShipmentCost> PendingShipmentCosts { get; set; }
        [InverseProperty(nameof(ShipmentCost.ShipmentCostType))]
        public virtual ICollection<ShipmentCost> ShipmentCosts { get; set; }
    }
}