// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ShippingCartSAPSalesOrderItem")]
    public partial class ShippingCartSapsalesOrderItem
    {
        [Key]
        [Column("ShippingCartSAPSalesOrderItemID")]
        public long ShippingCartSapsalesOrderItemId { get; set; }
        [Column("ShippingCartID")]
        public long ShippingCartId { get; set; }
        [Column("SAPSalesOrderItemID")]
        public long SapsalesOrderItemId { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal CartQuantity { get; set; }

        [ForeignKey(nameof(SapsalesOrderItemId))]
        [InverseProperty("ShippingCartSapsalesOrderItems")]
        public virtual SapsalesOrderItem SapsalesOrderItem { get; set; }
        [ForeignKey(nameof(ShippingCartId))]
        [InverseProperty("ShippingCartSapsalesOrderItems")]
        public virtual ShippingCart ShippingCart { get; set; }
    }
}