// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ShoppingCartWheatland")]
    public partial class ShoppingCartWheatland
    {
        [Key]
        [Column("ShoppingCartWheatlandID")]
        public long ShoppingCartWheatlandId { get; set; }
        [Column("ShoppingCartID")]
        public long ShoppingCartId { get; set; }
        [Column("SapMaterialID")]
        public long SapMaterialId { get; set; }
        [StringLength(10)]
        public string Status { get; set; }
        [Column("PlantID")]
        public long? PlantId { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal CartQuantity { get; set; }
        public int? Length { get; set; }
        [Column(TypeName = "date")]
        public DateTime? RequestedDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? RollingDate { get; set; }
        [StringLength(10)]
        public string Type { get; set; }
    }
}