// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ShoppingCartSAPRolling")]
    public partial class ShoppingCartSaprolling
    {
        [Key]
        [Column("ShoppingCartSAPRollingID")]
        public long ShoppingCartSaprollingId { get; set; }
        [Column("ShoppingCartID")]
        public long ShoppingCartId { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [Column("PlantID")]
        public long PlantId { get; set; }
        [Column("SAPMaterialID")]
        public long SapmaterialId { get; set; }
        [Column(TypeName = "date")]
        public DateTime RollDate { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal CartQuantity { get; set; }
        [Column("SAPRollingID")]
        public long? SaprollingId { get; set; }
        public int? LengthFeet { get; set; }
        public int? LengthInches { get; set; }
        public int? Bundling1 { get; set; }
        public int? Bundling2 { get; set; }
        public int? BundlingRound { get; set; }
        [Column("SAPTubeStandardID")]
        public long SaptubeStandardId { get; set; }
        [StringLength(250)]
        public string Note { get; set; }
        [Column(TypeName = "date")]
        public DateTime RequestedDate { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal AvailableQuantity { get; set; }
        [StringLength(1)]
        public string RecordSource { get; set; }
        [Column("SalesInstructionID")]
        [StringLength(50)]
        public string SalesInstructionId { get; set; }
        [Column("SpecificationID")]
        [StringLength(50)]
        public string SpecificationId { get; set; }

        [ForeignKey(nameof(PlantId))]
        [InverseProperty("ShoppingCartSaprollings")]
        public virtual Plant Plant { get; set; }
        [ForeignKey(nameof(SapmaterialId))]
        [InverseProperty("ShoppingCartSaprollings")]
        public virtual Sapmaterial Sapmaterial { get; set; }
        [ForeignKey(nameof(SaptubeStandardId))]
        [InverseProperty(nameof(SapcharacteristicOption.ShoppingCartSaprollings))]
        public virtual SapcharacteristicOption SaptubeStandard { get; set; }
        [ForeignKey(nameof(ShoppingCartId))]
        [InverseProperty("ShoppingCartSaprollings")]
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}