// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ShoppingCart")]
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            ShoppingCartSaprollings = new HashSet<ShoppingCartSaprolling>();
            ShoppingCartSapstocks = new HashSet<ShoppingCartSapstock>();
        }

        [Key]
        [Column("ShoppingCardID")]
        public long ShoppingCardId { get; set; }
        [Column("UserID")]
        public long UserId { get; set; }
        [StringLength(30)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(30)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("ShoppingCarts")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(ShoppingCartSaprolling.ShoppingCart))]
        public virtual ICollection<ShoppingCartSaprolling> ShoppingCartSaprollings { get; set; }
        [InverseProperty(nameof(ShoppingCartSapstock.ShoppingCart))]
        public virtual ICollection<ShoppingCartSapstock> ShoppingCartSapstocks { get; set; }
    }
}