// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("SoldToPriceSheetDefaultOption")]
    public partial class SoldToPriceSheetDefaultOption
    {
        [Key]
        [Column("SAPSoldToID")]
        public long SapsoldToId { get; set; }
        [Column("FLGSoldToPrice")]
        public bool FlgsoldToPrice { get; set; }
        public bool FlgShipToPrice { get; set; }
        [Required]
        [StringLength(255)]
        public string DefaultShiptos { get; set; }
        [Required]
        [StringLength(255)]
        public string DefaultUsers { get; set; }
        [Required]
        [Column("OtherEmailID")]
        [StringLength(500)]
        public string OtherEmailId { get; set; }
        [Required]
        [StringLength(50)]
        public string PriceSheetType { get; set; }
        [Required]
        [StringLength(50)]
        public string PriceSheetView { get; set; }
    }
}