// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("Square")]
    public partial class Square
    {
        [Key]
        [Column("SquareID")]
        public int SquareId { get; set; }
        [Column(TypeName = "decimal(9, 4)")]
        public decimal Size { get; set; }
        [StringLength(50)]
        public string MaterialGroup { get; set; }
    }
}