// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("State")]
    [Microsoft.EntityFrameworkCore.Index(nameof(CountryId), nameof(Abbreviation), Name = "IX_State", IsUnique = true)]
    public partial class State
    {
        public State()
        {
            Cities = new HashSet<City>();
        }

        [Key]
        [Column("StateID")]
        public long StateId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("CountryID")]
        public long CountryId { get; set; }
        [StringLength(3)]
        public string Abbreviation { get; set; }
        [Required]
        public bool? Active { get; set; }

        [ForeignKey(nameof(CountryId))]
        [InverseProperty("States")]
        public virtual Country Country { get; set; }
        [InverseProperty(nameof(City.State))]
        public virtual ICollection<City> Cities { get; set; }
    }
}