// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("Stock")]
    public partial class Stock
    {
        [Key]
        [Column("StockID")]
        public long StockId { get; set; }
        [Column("QuoteMaterialID")]
        public long QuoteMaterialId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(40)]
        public string Grade { get; set; }
        [Column("PlantID")]
        public long PlantId { get; set; }
        [Column(TypeName = "decimal(18, 4)")]
        public decimal TubeLength { get; set; }
        public int AvailablePieces { get; set; }
        [Column(TypeName = "decimal(17, 3)")]
        public decimal Weight { get; set; }
        [Required]
        [Column("UOM")]
        [StringLength(3)]
        public string Uom { get; set; }
        public int? Bundling1 { get; set; }
        public int? Bundling2 { get; set; }
        [Column("SAPCode")]
        [StringLength(50)]
        public string Sapcode { get; set; }
        [Column("SAPSalesOrderItemID")]
        public long? SapsalesOrderItemId { get; set; }
        public int? BundlingRound { get; set; }
        public bool? PlaceOnSalesOrder { get; set; }

        [ForeignKey(nameof(PlantId))]
        [InverseProperty("Stocks")]
        public virtual Plant Plant { get; set; }
        [ForeignKey(nameof(QuoteMaterialId))]
        [InverseProperty("Stocks")]
        public virtual QuoteMaterial QuoteMaterial { get; set; }
        [ForeignKey(nameof(SapsalesOrderItemId))]
        [InverseProperty("Stocks")]
        public virtual SapsalesOrderItem SapsalesOrderItem { get; set; }
    }
}