// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("Trailer")]
    public partial class Trailer
    {
        public Trailer()
        {
            ScrapSales = new HashSet<ScrapSale>();
        }

        [Key]
        [Column("TrailerID")]
        public long TrailerId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("SAPVendorID")]
        public long? SapvendorId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Weight { get; set; }
        public bool Active { get; set; }
        [Column("ScrapSAPSoldToID")]
        public long? ScrapSapsoldToId { get; set; }
        [Column("RandomLengthSAPSoldToID")]
        public long? RandomLengthSapsoldToId { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(50)]
        public string ChangedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ChagedDate { get; set; }
        [Column("previousWeight", TypeName = "decimal(18, 2)")]
        public decimal? PreviousWeight { get; set; }

        [ForeignKey(nameof(RandomLengthSapsoldToId))]
        [InverseProperty("Trailers")]
        public virtual RandomLengthSapsoldTo RandomLengthSapsoldTo { get; set; }
        [ForeignKey(nameof(SapvendorId))]
        [InverseProperty("Trailers")]
        public virtual Sapvendor Sapvendor { get; set; }
        [ForeignKey(nameof(ScrapSapsoldToId))]
        [InverseProperty("Trailers")]
        public virtual ScrapSapsoldTo ScrapSapsoldTo { get; set; }
        [InverseProperty(nameof(ScrapSale.Trailer))]
        public virtual ICollection<ScrapSale> ScrapSales { get; set; }
    }
}