// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Keyless]
    [Table("TZTimezone")]
    public partial class Tztimezone
    {
        [Column("zone_id")]
        public int? ZoneId { get; set; }
        [Required]
        [Column("abbreviation")]
        [StringLength(6)]
        public string Abbreviation { get; set; }
        [Column("time_start", TypeName = "decimal(11, 0)")]
        public decimal TimeStart { get; set; }
        [Column("gmt_offset")]
        public int GmtOffset { get; set; }
        [Required]
        [Column("dst")]
        [StringLength(1)]
        public string Dst { get; set; }

        [ForeignKey(nameof(ZoneId))]
        public virtual Tzzone Zone { get; set; }
    }
}