// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("TZZone")]
    public partial class Tzzone
    {
        [Key]
        [Column("zone_id")]
        public int ZoneId { get; set; }
        [Required]
        [Column("country_code")]
        [StringLength(2)]
        public string CountryCode { get; set; }
        [Required]
        [Column("zone_name")]
        [StringLength(35)]
        public string ZoneName { get; set; }

        [ForeignKey(nameof(CountryCode))]
        [InverseProperty(nameof(Tzcountry.Tzzones))]
        public virtual Tzcountry CountryCodeNavigation { get; set; }
    }
}