// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Keyless]
    [Table("UserApplicationRole")]
    [Microsoft.EntityFrameworkCore.Index(nameof(UserId), nameof(ApplicationRoleId), Name = "IX_UserApplicationRole_1", IsUnique = true)]
    public partial class UserApplicationRole
    {
        [Column("UserID")]
        public long UserId { get; set; }
        [Column("ApplicationRoleID")]
        public long ApplicationRoleId { get; set; }

        [ForeignKey(nameof(ApplicationRoleId))]
        public virtual ApplicationRole ApplicationRole { get; set; }
        [ForeignKey(nameof(UserId))]
        public virtual User User { get; set; }
    }
}