// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("WebReleasePlant")]
    public partial class WebReleasePlant
    {
        public WebReleasePlant()
        {
            WebReleasePlantSapsalesOrderItems = new HashSet<WebReleasePlantSapsalesOrderItem>();
        }

        [Key]
        [Column("WebReleasePlantID")]
        public long WebReleasePlantId { get; set; }
        [Column("WebReleaseID")]
        public long WebReleaseId { get; set; }
        [Column("PlantID")]
        public long PlantId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ExpectedDate { get; set; }
        [StringLength(20)]
        public string ExpectedTime { get; set; }
        [StringLength(4000)]
        public string CustomerComments { get; set; }
        public bool? Reviewed { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DepartureDate { get; set; }
        [Column("CSRComments")]
        [StringLength(4000)]
        public string Csrcomments { get; set; }
        public bool? Processed { get; set; }
        [StringLength(3)]
        public string OnOrBefore { get; set; }
        public long? XferToPlant { get; set; }
        [Column("STOSuccess")]
        public bool? Stosuccess { get; set; }
        [Column("STOPONumber")]
        [StringLength(35)]
        public string Stoponumber { get; set; }
        [StringLength(4000)]
        public string EtOutputMessages { get; set; }

        [ForeignKey(nameof(PlantId))]
        [InverseProperty("WebReleasePlants")]
        public virtual Plant Plant { get; set; }
        [ForeignKey(nameof(WebReleaseId))]
        [InverseProperty("WebReleasePlants")]
        public virtual WebRelease WebRelease { get; set; }
        [InverseProperty(nameof(WebReleasePlantSapsalesOrderItem.WebReleasePlant))]
        public virtual ICollection<WebReleasePlantSapsalesOrderItem> WebReleasePlantSapsalesOrderItems { get; set; }
    }
}