// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Keyless]
    [Table("WebRelasePlantSAPSalesOrderItemSAPDeliveryItem")]
    [Microsoft.EntityFrameworkCore.Index(nameof(SapdeliveryItemId), Name = "missing_index_12_11_WebRelasePlantSAPSalesOrderItemS")]
    public partial class WebRelasePlantSapsalesOrderItemSapdeliveryItem
    {
        [Column("WebReleasePlantSAPSalesOrderItemID")]
        public long WebReleasePlantSapsalesOrderItemId { get; set; }
        [Column("SAPDeliveryItemID")]
        public long SapdeliveryItemId { get; set; }

        [ForeignKey(nameof(SapdeliveryItemId))]
        public virtual SapdeliveryItem SapdeliveryItem { get; set; }
        [ForeignKey(nameof(WebReleasePlantSapsalesOrderItemId))]
        public virtual WebReleasePlantSapsalesOrderItem WebReleasePlantSapsalesOrderItem { get; set; }
    }
}