// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("WebRelease")]
    public partial class WebRelease
    {
        public WebRelease()
        {
            WebReleasePlants = new HashSet<WebReleasePlant>();
        }

        [Key]
        [Column("WebReleaseID")]
        public long WebReleaseId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateTime { get; set; }
        [Column("UserID")]
        public long UserId { get; set; }
        [StringLength(20)]
        public string CustReleaseNumber { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("WebReleases")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(WebReleasePlant.WebRelease))]
        public virtual ICollection<WebReleasePlant> WebReleasePlants { get; set; }
    }
}