// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("WTCPipe_BNB")]
    public partial class WtcpipeBnb
    {
        [Key]
        [Column("Material_ID")]
        public int MaterialId { get; set; }
        [Column("Material_Number")]
        [StringLength(25)]
        public string MaterialNumber { get; set; }
    }
}