// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ZG01")]
    public partial class Zg01
    {
        [Key]
        [Column("GradeXtraID")]
        public long GradeXtraId { get; set; }
        [Column("SAPSoldtoID")]
        public long? SapsoldtoId { get; set; }
        [Column("SAPTubeStandardID")]
        public long SaptubeStandardId { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal Rate { get; set; }
        [Required]
        [StringLength(10)]
        public string Currency { get; set; }
        public long Per { get; set; }
        [Required]
        [StringLength(10)]
        public string Unit { get; set; }
        [Column(TypeName = "date")]
        public DateTime ValidFrom { get; set; }
        [Column(TypeName = "date")]
        public DateTime ValidTo { get; set; }

        [ForeignKey(nameof(SaptubeStandardId))]
        [InverseProperty(nameof(SapcharacteristicOption.Zg01s))]
        public virtual SapcharacteristicOption SaptubeStandard { get; set; }
    }
}