// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ZR00")]
    public partial class Zr00
    {
        [Key]
        [Column("conditionID")]
        public long ConditionId { get; set; }
        [Column("SAPSoldtoID")]
        public long SapsoldtoId { get; set; }
        [Column("SAPMaterialPricingGroupID")]
        public long SapmaterialPricingGroupId { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal Rate { get; set; }
        [Required]
        [StringLength(10)]
        public string Currency { get; set; }
        public long Per { get; set; }
        [Required]
        [StringLength(10)]
        public string Unit { get; set; }
        [Column(TypeName = "date")]
        public DateTime ValidFrom { get; set; }
        [Column(TypeName = "date")]
        public DateTime ValidTo { get; set; }

        [ForeignKey(nameof(SapmaterialPricingGroupId))]
        [InverseProperty(nameof(SapcharacteristicOption.Zr00s))]
        public virtual SapcharacteristicOption SapmaterialPricingGroup { get; set; }
        [ForeignKey(nameof(SapsoldtoId))]
        [InverseProperty(nameof(SapshipTo.Zr00s))]
        public virtual SapshipTo Sapsoldto { get; set; }
    }
}