// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ZR01")]
    public partial class Zr01
    {
        [Key]
        [Column("ZR01ID")]
        public long Zr01id { get; set; }
        [Column("SAPSoldtoID")]
        public long SapsoldtoId { get; set; }
        [Column("SAPPricingGroupID")]
        public long SappricingGroupId { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal Rate { get; set; }
        [Required]
        [StringLength(10)]
        public string Currency { get; set; }
        public long Per { get; set; }
        [Required]
        [StringLength(10)]
        public string Unit { get; set; }
        [Column(TypeName = "date")]
        public DateTime ValidFrom { get; set; }
        [Column(TypeName = "date")]
        public DateTime ValidTo { get; set; }

        [ForeignKey(nameof(SappricingGroupId))]
        [InverseProperty(nameof(SapcharacteristicOption.Zr01s))]
        public virtual SapcharacteristicOption SappricingGroup { get; set; }
        [ForeignKey(nameof(SapsoldtoId))]
        [InverseProperty(nameof(SapshipTo.Zr01s))]
        public virtual SapshipTo Sapsoldto { get; set; }
    }
}