// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JMC.Portal.Business.PortalModels
{
    [Table("ZR04")]
    public partial class Zr04
    {
        [Key]
        [Column("ZR04ID")]
        public long Zr04id { get; set; }
        [Column("SAPSoldtoID")]
        public long SapsoldtoId { get; set; }
        [Column("SAPMaterialGroupID")]
        public long SapmaterialGroupId { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal Rate { get; set; }
        [Required]
        [StringLength(10)]
        public string Currency { get; set; }
        public long Per { get; set; }
        [Required]
        [StringLength(10)]
        public string Unit { get; set; }
        [Column(TypeName = "date")]
        public DateTime ValidFrom { get; set; }
        [Column(TypeName = "date")]
        public DateTime ValidTo { get; set; }

        [ForeignKey(nameof(SapmaterialGroupId))]
        [InverseProperty(nameof(SapcharacteristicOption.Zr04s))]
        public virtual SapcharacteristicOption SapmaterialGroup { get; set; }
        [ForeignKey(nameof(SapsoldtoId))]
        [InverseProperty(nameof(SapsoldTo.Zr04s))]
        public virtual SapsoldTo Sapsoldto { get; set; }
    }
}