//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SysXml = System.Xml;

namespace JMC.Portal.Business.HSSPortalAPOSales
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="JMC.Portal.Business.HSSPortalAPOSales.ZWS_HSS_PORTAL_APO_SALES")]
    public interface ZWS_HSS_PORTAL_APO_SALES
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_HSS_PORTAL_APO_SALES:ZfmGetW" +
            "hRollingRequest", ReplyAction="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_HSS_PORTAL_APO_SALES:ZfmGetW" +
            "hRollingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JMC.Portal.Business.HSSPortalAPOSales.ZfmGetWhRollingResponse1> ZfmGetWhRollingAsync(JMC.Portal.Business.HSSPortalAPOSales.ZfmGetWhRollingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_HSS_PORTAL_APO_SALES:ZfmGetH" +
            "ssPortalapoRollingsRequest", ReplyAction="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_HSS_PORTAL_APO_SALES:ZfmGetH" +
            "ssPortalapoRollingsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JMC.Portal.Business.HSSPortalAPOSales.ZfmGetHssPortalapoRollingsResponse1> ZfmGetHssPortalapoRollingsAsync(JMC.Portal.Business.HSSPortalAPOSales.ZfmGetHssPortalapoRollingsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmGetWhRolling
    {
        
        private decimal[] itDiaField;
        
        private string[] itGradeField;
        
        private string[] itLocnoField;
        
        private string[] itPlanmatField;
        
        private string[] itShapeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public decimal[] ItDia
        {
            get
            {
                return this.itDiaField;
            }
            set
            {
                this.itDiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ItGrade
        {
            get
            {
                return this.itGradeField;
            }
            set
            {
                this.itGradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ItLocno
        {
            get
            {
                return this.itLocnoField;
            }
            set
            {
                this.itLocnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ItPlanmat
        {
            get
            {
                return this.itPlanmatField;
            }
            set
            {
                this.itPlanmatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ItShape
        {
            get
            {
                return this.itShapeField;
            }
            set
            {
                this.itShapeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstHssPortalRolling
    {
        
        private string materialNumberField;
        
        private string plantField;
        
        private string planningMaterialField;
        
        private string rollingDateField;
        
        private decimal plannedField;
        
        private decimal allocatedField;
        
        private decimal weightPerFootField;
        
        private decimal combFreeField;
        
        private string bFixedField;
        
        private string resourceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MaterialNumber
        {
            get
            {
                return this.materialNumberField;
            }
            set
            {
                this.materialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Plant
        {
            get
            {
                return this.plantField;
            }
            set
            {
                this.plantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PlanningMaterial
        {
            get
            {
                return this.planningMaterialField;
            }
            set
            {
                this.planningMaterialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string RollingDate
        {
            get
            {
                return this.rollingDateField;
            }
            set
            {
                this.rollingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Planned
        {
            get
            {
                return this.plannedField;
            }
            set
            {
                this.plannedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Allocated
        {
            get
            {
                return this.allocatedField;
            }
            set
            {
                this.allocatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal WeightPerFoot
        {
            get
            {
                return this.weightPerFootField;
            }
            set
            {
                this.weightPerFootField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal CombFree
        {
            get
            {
                return this.combFreeField;
            }
            set
            {
                this.combFreeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string BFixed
        {
            get
            {
                return this.bFixedField;
            }
            set
            {
                this.bFixedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ResourceName
        {
            get
            {
                return this.resourceNameField;
            }
            set
            {
                this.resourceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstPlantNumber
    {
        
        private string plantNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PlantNumber
        {
            get
            {
                return this.plantNumberField;
            }
            set
            {
                this.plantNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstMaterialNumber
    {
        
        private string materialNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MaterialNumber
        {
            get
            {
                return this.materialNumberField;
            }
            set
            {
                this.materialNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZatasGradeGrp
    {
        
        private string gradeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZppPortalRolling
    {
        
        private string planningMaterialField;
        
        private string locnoField;
        
        private string resourceNameField;
        
        private string versionField;
        
        private string blockIdField;
        
        private string runNumberField;
        
        private string blkNumberField;
        
        private string startDateField;
        
        private string endDateField;
        
        private decimal plannedTonsField;
        
        private decimal bookedCapField;
        
        private decimal combFreeCapField;
        
        private decimal reservedCapField;
        
        private decimal stockOrdField;
        
        private decimal stockReqField;
        
        private string closedField;
        
        private string shapeField;
        
        private decimal gaugeField;
        
        private string gradeGroupField;
        
        private string maktxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PlanningMaterial
        {
            get
            {
                return this.planningMaterialField;
            }
            set
            {
                this.planningMaterialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Locno
        {
            get
            {
                return this.locnoField;
            }
            set
            {
                this.locnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ResourceName
        {
            get
            {
                return this.resourceNameField;
            }
            set
            {
                this.resourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BlockId
        {
            get
            {
                return this.blockIdField;
            }
            set
            {
                this.blockIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string RunNumber
        {
            get
            {
                return this.runNumberField;
            }
            set
            {
                this.runNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string BlkNumber
        {
            get
            {
                return this.blkNumberField;
            }
            set
            {
                this.blkNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal PlannedTons
        {
            get
            {
                return this.plannedTonsField;
            }
            set
            {
                this.plannedTonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal BookedCap
        {
            get
            {
                return this.bookedCapField;
            }
            set
            {
                this.bookedCapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal CombFreeCap
        {
            get
            {
                return this.combFreeCapField;
            }
            set
            {
                this.combFreeCapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal ReservedCap
        {
            get
            {
                return this.reservedCapField;
            }
            set
            {
                this.reservedCapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal StockOrd
        {
            get
            {
                return this.stockOrdField;
            }
            set
            {
                this.stockOrdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal StockReq
        {
            get
            {
                return this.stockReqField;
            }
            set
            {
                this.stockReqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Closed
        {
            get
            {
                return this.closedField;
            }
            set
            {
                this.closedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Shape
        {
            get
            {
                return this.shapeField;
            }
            set
            {
                this.shapeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public decimal Gauge
        {
            get
            {
                return this.gaugeField;
            }
            set
            {
                this.gaugeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string GradeGroup
        {
            get
            {
                return this.gradeGroupField;
            }
            set
            {
                this.gradeGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Maktx
        {
            get
            {
                return this.maktxField;
            }
            set
            {
                this.maktxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiret2
    {
        
        private string typeField;
        
        private string idField;
        
        private string numberField;
        
        private string messageField;
        
        private string logNoField;
        
        private string logMsgNoField;
        
        private string messageV1Field;
        
        private string messageV2Field;
        
        private string messageV3Field;
        
        private string messageV4Field;
        
        private string parameterField;
        
        private int rowField;
        
        private string fieldField;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LogNo
        {
            get
            {
                return this.logNoField;
            }
            set
            {
                this.logNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LogMsgNo
        {
            get
            {
                return this.logMsgNoField;
            }
            set
            {
                this.logMsgNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MessageV1
        {
            get
            {
                return this.messageV1Field;
            }
            set
            {
                this.messageV1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MessageV2
        {
            get
            {
                return this.messageV2Field;
            }
            set
            {
                this.messageV2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MessageV3
        {
            get
            {
                return this.messageV3Field;
            }
            set
            {
                this.messageV3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MessageV4
        {
            get
            {
                return this.messageV4Field;
            }
            set
            {
                this.messageV4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int Row
        {
            get
            {
                return this.rowField;
            }
            set
            {
                this.rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=SysXml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string System
        {
            get
            {
                return this.systemField;
            }
            set
            {
                this.systemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmGetWhRollingResponse
    {
        
        private Bapiret2[] etReturnField;
        
        private ZppPortalRolling[] etRollingTabField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] EtReturn
        {
            get
            {
                return this.etReturnField;
            }
            set
            {
                this.etReturnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZppPortalRolling[] EtRollingTab
        {
            get
            {
                return this.etRollingTabField;
            }
            set
            {
                this.etRollingTabField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfmGetWhRollingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public JMC.Portal.Business.HSSPortalAPOSales.ZfmGetWhRolling ZfmGetWhRolling;
        
        public ZfmGetWhRollingRequest()
        {
        }
        
        public ZfmGetWhRollingRequest(JMC.Portal.Business.HSSPortalAPOSales.ZfmGetWhRolling ZfmGetWhRolling)
        {
            this.ZfmGetWhRolling = ZfmGetWhRolling;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfmGetWhRollingResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public JMC.Portal.Business.HSSPortalAPOSales.ZfmGetWhRollingResponse ZfmGetWhRollingResponse;
        
        public ZfmGetWhRollingResponse1()
        {
        }
        
        public ZfmGetWhRollingResponse1(JMC.Portal.Business.HSSPortalAPOSales.ZfmGetWhRollingResponse ZfmGetWhRollingResponse)
        {
            this.ZfmGetWhRollingResponse = ZfmGetWhRollingResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmGetHssPortalapoRollings
    {
        
        private string imIncludeClosedField;
        
        private string imMaterialGroupField;
        
        private ZatasGradeGrp[] itGradesField;
        
        private ZstMaterialNumber[] itMaterialNumbersField;
        
        private ZstPlantNumber[] itPlantNumbersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ImIncludeClosed
        {
            get
            {
                return this.imIncludeClosedField;
            }
            set
            {
                this.imIncludeClosedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ImMaterialGroup
        {
            get
            {
                return this.imMaterialGroupField;
            }
            set
            {
                this.imMaterialGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZatasGradeGrp[] ItGrades
        {
            get
            {
                return this.itGradesField;
            }
            set
            {
                this.itGradesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstMaterialNumber[] ItMaterialNumbers
        {
            get
            {
                return this.itMaterialNumbersField;
            }
            set
            {
                this.itMaterialNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstPlantNumber[] ItPlantNumbers
        {
            get
            {
                return this.itPlantNumbersField;
            }
            set
            {
                this.itPlantNumbersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmGetHssPortalapoRollingsResponse
    {
        
        private ZstHssPortalRolling[] etHssPortalRollingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstHssPortalRolling[] EtHssPortalRollings
        {
            get
            {
                return this.etHssPortalRollingsField;
            }
            set
            {
                this.etHssPortalRollingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfmGetHssPortalapoRollingsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public JMC.Portal.Business.HSSPortalAPOSales.ZfmGetHssPortalapoRollings ZfmGetHssPortalapoRollings;
        
        public ZfmGetHssPortalapoRollingsRequest()
        {
        }
        
        public ZfmGetHssPortalapoRollingsRequest(JMC.Portal.Business.HSSPortalAPOSales.ZfmGetHssPortalapoRollings ZfmGetHssPortalapoRollings)
        {
            this.ZfmGetHssPortalapoRollings = ZfmGetHssPortalapoRollings;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfmGetHssPortalapoRollingsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public JMC.Portal.Business.HSSPortalAPOSales.ZfmGetHssPortalapoRollingsResponse ZfmGetHssPortalapoRollingsResponse;
        
        public ZfmGetHssPortalapoRollingsResponse1()
        {
        }
        
        public ZfmGetHssPortalapoRollingsResponse1(JMC.Portal.Business.HSSPortalAPOSales.ZfmGetHssPortalapoRollingsResponse ZfmGetHssPortalapoRollingsResponse)
        {
            this.ZfmGetHssPortalapoRollingsResponse = ZfmGetHssPortalapoRollingsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ZWS_HSS_PORTAL_APO_SALESChannel : JMC.Portal.Business.HSSPortalAPOSales.ZWS_HSS_PORTAL_APO_SALES, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ZWS_HSS_PORTAL_APO_SALESClient : System.ServiceModel.ClientBase<JMC.Portal.Business.HSSPortalAPOSales.ZWS_HSS_PORTAL_APO_SALES>, JMC.Portal.Business.HSSPortalAPOSales.ZWS_HSS_PORTAL_APO_SALES
    {
        public ZWS_HSS_PORTAL_APO_SALESClient()
        {
        }

        public ZWS_HSS_PORTAL_APO_SALESClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ZWS_HSS_PORTAL_APO_SALESClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JMC.Portal.Business.HSSPortalAPOSales.ZfmGetWhRollingResponse1> JMC.Portal.Business.HSSPortalAPOSales.ZWS_HSS_PORTAL_APO_SALES.ZfmGetWhRollingAsync(JMC.Portal.Business.HSSPortalAPOSales.ZfmGetWhRollingRequest request)
        {
            return base.Channel.ZfmGetWhRollingAsync(request);
        }
        
        public System.Threading.Tasks.Task<JMC.Portal.Business.HSSPortalAPOSales.ZfmGetWhRollingResponse1> ZfmGetWhRollingAsync(JMC.Portal.Business.HSSPortalAPOSales.ZfmGetWhRolling ZfmGetWhRolling)
        {
            JMC.Portal.Business.HSSPortalAPOSales.ZfmGetWhRollingRequest inValue = new JMC.Portal.Business.HSSPortalAPOSales.ZfmGetWhRollingRequest();
            inValue.ZfmGetWhRolling = ZfmGetWhRolling;
            return ((JMC.Portal.Business.HSSPortalAPOSales.ZWS_HSS_PORTAL_APO_SALES)(this)).ZfmGetWhRollingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JMC.Portal.Business.HSSPortalAPOSales.ZfmGetHssPortalapoRollingsResponse1> JMC.Portal.Business.HSSPortalAPOSales.ZWS_HSS_PORTAL_APO_SALES.ZfmGetHssPortalapoRollingsAsync(JMC.Portal.Business.HSSPortalAPOSales.ZfmGetHssPortalapoRollingsRequest request)
        {
            return base.Channel.ZfmGetHssPortalapoRollingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<JMC.Portal.Business.HSSPortalAPOSales.ZfmGetHssPortalapoRollingsResponse1> ZfmGetHssPortalapoRollingsAsync(JMC.Portal.Business.HSSPortalAPOSales.ZfmGetHssPortalapoRollings ZfmGetHssPortalapoRollings)
        {
            JMC.Portal.Business.HSSPortalAPOSales.ZfmGetHssPortalapoRollingsRequest inValue = new JMC.Portal.Business.HSSPortalAPOSales.ZfmGetHssPortalapoRollingsRequest();
            inValue.ZfmGetHssPortalapoRollings = ZfmGetHssPortalapoRollings;
            return ((JMC.Portal.Business.HSSPortalAPOSales.ZWS_HSS_PORTAL_APO_SALES)(this)).ZfmGetHssPortalapoRollingsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
